(function (){ var e="",aa="\x00",h=" ",ba=" (",ca=" (Google)",da=' name="',ea=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)',ga=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678) alpha(opacity=50)',ha=' type="',ia=" x ",ja='"',ka='"trebuchet ms",verdana,arial,sans-serif',la="#",ma="#000",na="#fff",oa="%",pa="%$1",qa="%2525",ra="%s",l="&",
sa="&#0;",ua="&#39;",va="&action=",wa="&amp;",xa="&func=",ya="&gt;",za="&lt;",Aa="&nbsp;",Ba="&quot;",Ca="&sectionId=",Da="&widgetId=",Ea="&widgetType=",Fa="'",Ga="' of type ",Ha="(",Ia="(\\d*)(\\D*)",Ja=")",Ka="*",La=",",Ma="-140px",Na="-225px",Oa=".",Pa=".01",Qa=".5",Ra=".js",Ta=".previewMode .postCommentButtonHolder { padding-top: 22px; }\n",Ua=".x",Va=".y",Wa="/",Xa="//",Ya="//img2.blogblog.com/img/icon_inprogress.gif",Za="/comment-iframe-bg.g",$a="/rearrange?blogID=",ab="0",bb="1",cb="100%",
db="1000",eb="10px",fb="1px solid #aaa",gb="1px solid transparent",hb="200px",ib="24px",jb="28px",kb="50% 0",lb="600px",mb="75px",nb=":",ob=": ",pb=";\nfont-family: ",qb=";}\n",rb="<",n="=",sb=">",tb="?",ub="?widgetId=",vb="@",wb="AIM",xb="AIM username:",yb="ANON",zb="ARIA attribute cannot be empty.",Ab="An error occurred while contacting the server.",Bb="An object listener must have handleEvent method.",Cb="Anonymous",Db="Assertion failed",Eb="BODY",Fb="CSS1Compat",Gb="CURRENT",Hb="Comment should not be empty",
Ib="Content length exceeds 1MB. Please abridge.",Jb="Content-Type",Kb="DIV",Lb="Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?",Mb="Expected number but got %s: %s.",Nb="Expected string but got %s: %s.",Ob="FIELDSET",Pb="GET",Qb="GOOGLE",Rb="Google Account",Sb="HEAD",Tb="INPUT",Ub="LJ",Vb="Listener can not be null.",Wb="LiveJournal",Xb="LiveJournal username:",Yb="MSXML2.XMLHTTP",Zb="MSXML2.XMLHTTP.3.0",$b="MSXML2.XMLHTTP.6.0",ac="Microsoft Internet Explorer",
bc="Microsoft.XMLHTTP",cc="NAMEURL",dc="NONE",ec="Name should not be empty",fc="Name/URL",gc="No such ARIA attribute expanded",hc="No such ARIA role tab",ic="Node cannot be null or undefined.",jc="OPENID",kc="OpenID",lc="POST",mc="Please choose a profile",nc="Preview",oc="SCRIPT",pc="STYLE",qc="SafeStyleSheet{",rc="Select profile...",sc="SubscribeByEmail",tc="TP",uc="The URL should not be empty",vc="The username should not be empty",wc="TypePad",xc="TypePad username:",yc="UnsubscribeByEmail",zc="WP",
Ac="WordPress",Bc="WordPress username:",Cc="X",Dc="[object Array]",Ec="[object Function]",Fc="[object Window]",Gc="]",Hc="_",Ic="_OnWidgetDeleted",Jc="__gjsload__",Kc="_asynchronousFileUploadIframe",Lc="_changeImageLink",Mc="_imageChoiceTable",Nc="_imgFileNameError",Oc="_imgFileNameInput",Pc="_imgSrcFromPCRadio",Qc="_imgSrcFromWebRadio",Rc="_imgUrlTextError",Sc="_imgUrlTextInput",Tc="_picImg",Uc="a",Vc="a:link, a:visited, a:active, a:hover { color: ",Wc="abort",Xc="absolute",Yc="action",Zc="action=",
$c="additions text",ad="addnew",bd="ajaxAction",cd="allHolder",dd="alpha(opacity=1)",ed="animate",fd="anonNameField",gd="anonUrlField",hd="application/x-www-form-urlencoded;charset=utf-8",id="aria-",jd="aria-expanded",kd="array",ld="arraybuffer",md="begin",nd="bgint",od="bgresponse",pd="block",qd="blogID",rd="blogger-clickTrap singleton-element",sd="blur",td="body { color: ",ud="button",vd="call",wd="captcha-error",xd="center",yd="change",zd="checkbox",Ad="checked",Bd="chooseWidget",Cd="class",Dd=
"click",Ed="commentBody-err",Fd="commentBodyField",Gd="commentDash",Hd="commentForm",Id="commentSubscriptionForm",Jd="compact",p="complete",Kd="config",Ld="configure",Md="content-type",Nd="data-",Od="default",Pd="delete",Qd="destroy",Rd="disabled",Sd="display",Td="displayModeFull",Ud="displayModeLayout",Vd="displayModeNone",Wd="displayModeSnippet",Xd="div",Yd="downloadprogress",Zd="edit-link",$d="editButton",ae="editlink",be="encodedIds",ce="encodedSelectedId",de="end",ee="error",fe="error-details",
ge="errorbox-bad errormsg",he="errorbox-good",ie="errormessage_",je="event",ke="expanded",le="expected object of type SafeStyleSheet, got '",me="expression(this.parentNode.clientHeight)",ne="false",oe="file",pe="finish",qe="focus",re="for",se="form",q="function",te="g",ue="genericOpenIdDialogErrorHolder",ve="genericOpenIdIdentityHolder",we="goog-zippy-collapsed",xe="goog-zippy-content",ye="goog-zippy-expanded",ze="goog-zippy-header",Ae="goog.dom.setTextContent expects a non-null value for node",Be=
"goog.net.EventType.PROGRESS is of the same type as raw XHR progress.",Ce="hidden",De="href",Ee="http",Fe="http://",Ge="http://openid.aol.com/{username}",He="http://{username}.livejournal.com",Ie="http://{username}.wordpress.com",Je="https://profile.typepad.com/{username}",Ke="id",Le="id-error",Me="identity-type-",Ne="identityControlsHolder",Oe="identityHolder",Pe="identityMenu",Qe="iemode",Re="image",Se="imageUpload.do",Te="img",Ue="infinite loop",Ve="inline",We="input",Xe="keydown",Ye="keypress",
Ze="keyup",$e="layout-title",af="main-error",bf="main-error-holder",cf="main-status",df="main-status-holder",ef="mouseout",ff="mouseover",gf="mozResponseArrayBuffer",hf="multipart/form-data",jf="nameUrlDialogErrorHolder",kf="nameUrlIdentityHolder",lf="native code",mf="no type",nf="no widget for ",t="none",of="null",pf="number",qf="o",rf="object",sf="off",tf="on",uf="oninput",vf="onprogress",wf="openIdDialogErrorHolder",xf="openIdIdentityHolder",yf="openIdUriDisplayPrefix",zf="openIdUriDisplaySuffix",
Af="openIdUriDisplayUsername",Bf="openIdUriField",Cf="openIdUserNameField",Df="openIdUsernameLabel",Ef="option",Ff="overflow:hidden",Gf="page",Hf="pageID",If="play",Jf="polyfill",Kf="postCommentPreview",Lf="postCommentSubmit",Mf="previewHolder",Nf="previewMode",Of="progress",Pf="px",Qf="radio",Rf="ready",Sf="readystatechange",Tf="reset",Uf="response",Vf="responseType=js",Wf="resume",Xf="role",Yf="rotate(-45deg)",Zf="sectionId",$f="sectionWidth",ag="security_token",bg="select",cg="select-multiple",
dg="select-one",eg="set-comment-editor-height ",fg="settingsButton",gg="showPreview",hg="singleton-element",ig="span",jg="splice",kg="status-message",lg="status-message-inner",mg="stop",ng="string",og="style",pg="submit",qg="subscribeButtonHolder",rg="success",sg="tab",tg="text",ug="text/javascript",vg="textContent",wg="timeout",xg="toggle",yg="true",zg="type_error:SafeStyleSheet",Ag="uploadprogress",Bg="use",Cg="username",Dg="var ",Eg="vertical",Fg="viewBox",Gg="white",Hg="widget-content",Ig="widget-wrap1",
Jg="widget-wrap2",Kg="widget-wrap3",Lg="widgetId=",Mg="widgetType",Ng="widgetType=",Og="width=570,height=600,left=75,top=20,resizable=yes,scrollbars=yes",Pg="window",Qg="withCredentials",Rg="xlink:href",Sg="{username}",Tg="}",u,Ug=Ug||{},v=this,w=function(a){return void 0!==a},x=function(a,b,c){a=a.split(Oa);c=c||v;a[0]in c||!c.execScript||c.execScript(Dg+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&w(b)?c[d]=b:c=c[d]?c[d]:c[d]={}},Vg=function(){},Wg=function(a){a.Zf=function(){return a.Pd?
a.Pd:a.Pd=new a}},Xg=function(a){var b=typeof a;if(b==rf)if(a){if(a instanceof Array)return kd;if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c==Fc)return rf;if(c==Dc||typeof a.length==pf&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(jg))return kd;if(c==Ec||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable(vd))return q}else return of;else if(b==q&&"undefined"==typeof a.call)return rf;
return b},y=function(a){return Xg(a)==kd},Yg=function(a){var b=Xg(a);return b==kd||b==rf&&typeof a.length==pf},z=function(a){return typeof a==ng},Zg=function(a){return typeof a==pf},$g=function(a){return Xg(a)==q},ah=function(a){var b=typeof a;return b==rf&&null!=a||b==q},bh="closure_uid_"+(1E9*Math.random()>>>0),ch=0,dh=function(a,b,c){return a.call.apply(a.bind,arguments)},eh=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=
Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},A=function(a,b,c){A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf(lf)?dh:eh;return A.apply(null,arguments)},fh=Date.now||function(){return+new Date},B=function(a,b){function c(){}c.prototype=b.prototype;a.h=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.pj=function(a,c,g){for(var k=Array(arguments.length-2),m=2;m<arguments.length;m++)k[m-
2]=arguments[m];return b.prototype[c].apply(a,k)}};var gh=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,gh);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};B(gh,Error);gh.prototype.name="CustomError";var hh;var ih=function(a,b){for(var c=a.split(ra),d=e,f=Array.prototype.slice.call(arguments,1);f.length&&1<c.length;)d+=c.shift()+f.shift();return d+c.join(ra)},jh=function(a){return a.replace(/(\r\n|\r|\n)+/g,h)},kh=function(a){return a.replace(/\xa0|[ \t]+/g,h)},lh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,e)},th=function(a,b){if(b)a=a.replace(mh,wa).replace(nh,za).replace(oh,ya).replace(ph,Ba).replace(qh,ua).replace(rh,sa);else{if(!sh.test(a))return a;
-1!=a.indexOf(l)&&(a=a.replace(mh,wa));-1!=a.indexOf(rb)&&(a=a.replace(nh,za));-1!=a.indexOf(sb)&&(a=a.replace(oh,ya));-1!=a.indexOf(ja)&&(a=a.replace(ph,Ba));-1!=a.indexOf(Fa)&&(a=a.replace(qh,ua));-1!=a.indexOf(aa)&&(a=a.replace(rh,sa))}return a},mh=/&/g,nh=/</g,oh=/>/g,ph=/"/g,qh=/'/g,rh=/\x00/g,sh=/[\x00&<>"']/,uh=function(a,b){return a<b?-1:a>b?1:0};var vh=function(a,b){b.unshift(a);gh.call(this,ih.apply(null,b));b.shift()};B(vh,gh);vh.prototype.name="AssertionError";
var wh=function(a,b,c,d){var f=Db;if(c)var f=f+(ob+c),g=d;else a&&(f+=ob+a,g=b);throw new vh(e+f,g||[]);},C=function(a,b,c){a||wh(e,null,b,Array.prototype.slice.call(arguments,2));return a},xh=function(a,b){throw new vh("Failure"+(a?ob+a:e),Array.prototype.slice.call(arguments,1));},D=function(a,b,c){Zg(a)||wh(Mb,[Xg(a),a],b,Array.prototype.slice.call(arguments,2));return a},yh=function(a,b,c){z(a)||wh(Nb,[Xg(a),a],b,Array.prototype.slice.call(arguments,2));return a};var zh=Array.prototype.indexOf?function(a,b,c){C(null!=a.length);return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(z(a))return z(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ah=Array.prototype.lastIndexOf?function(a,b,c){C(null!=a.length);return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(z(a))return z(b)&&1==
b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1},Bh=Array.prototype.forEach?function(a,b,c){C(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=z(a)?a.split(e):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},Ch=Array.prototype.filter?function(a,b,c){C(null!=a.length);return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,k=z(a)?a.split(e):a,m=0;m<d;m++)if(m in k){var r=k[m];b.call(c,r,m,a)&&(f[g++]=
r)}return f},Dh=Array.prototype.some?function(a,b,c){C(null!=a.length);return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=z(a)?a.split(e):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1},Eh=function(a,b,c){a:{for(var d=a.length,f=z(a)?a.split(e):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a)){b=g;break a}b=-1}return 0>b?null:z(a)?a.charAt(b):a[b]},E=function(a,b){return 0<=zh(a,b)},Fh=function(a){if(!y(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0},
Hh=function(a,b){var c=zh(a,b),d;(d=0<=c)&&Gh(a,c);return d},Gh=function(a,b){C(null!=a.length);return 1==Array.prototype.splice.call(a,b,1).length},Ih=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)},Jh=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Kh=function(a,b,c){C(null!=a.length);return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Lh=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Mh=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Nh=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Oh=function(a,b){return null!==a&&b in a},Ph=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1},Qh=function(a){for(var b in a)return!1;return!0},Rh="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Sh=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=
arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<Rh.length;g++)c=Rh[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var F;a:{var Th=v.navigator;if(Th){var Uh=Th.userAgent;if(Uh){F=Uh;break a}}F=e};var Wh=function(){this.Ec=e;this.hf=Vh},Vh={};Wh.prototype.toString=function(){return qc+this.Ec+Tg};Wh.prototype.tg=function(a){this.Ec=a;return this};var Yh=function(a){Xh();return(new Wh).tg(a)},Xh=Vg;var Zh=function(a,b){this.width=a;this.height=b};u=Zh.prototype;u.clone=function(){return new Zh(this.width,this.height)};u.toString=function(){return Ha+this.width+ia+this.height+Ja};u.Ef=function(){return this.width*this.height};u.isEmpty=function(){return!this.Ef()};u.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var $h=-1!=F.indexOf("Opera")||-1!=F.indexOf("OPR"),G=-1!=F.indexOf("Trident")||-1!=F.indexOf("MSIE"),ai=-1!=F.indexOf("Edge"),bi=-1!=F.indexOf("Gecko")&&!(-1!=F.toLowerCase().indexOf("webkit")&&-1==F.indexOf("Edge"))&&!(-1!=F.indexOf("Trident")||-1!=F.indexOf("MSIE"))&&-1==F.indexOf("Edge"),ci=-1!=F.toLowerCase().indexOf("webkit")&&-1==F.indexOf("Edge"),di=function(){var a=v.document;return a?a.documentMode:void 0},ei;
a:{var fi=e,gi=function(){var a=F;if(bi)return/rv\:([^\);]+)(\)|;)/.exec(a);if(ai)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ci)return/WebKit\/(\S+)/.exec(a);if($h)return/(?:Version)[ \/]?(\S+)/.exec(a)}();gi&&(fi=gi?gi[1]:e);if(G){var hi=di();if(null!=hi&&hi>parseFloat(fi)){ei=String(hi);break a}}ei=fi}
var ii=ei,ji={},H=function(a){var b;if(!(b=ji[a])){b=0;for(var c=lh(String(ii)).split(Oa),d=lh(String(a)).split(Oa),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var k=c[g]||e,m=d[g]||e,r=RegExp(Ia,te),ta=RegExp(Ia,te);do{var X=r.exec(k)||[e,e,e],Sa=ta.exec(m)||[e,e,e];if(0==X[0].length&&0==Sa[0].length)break;b=uh(0==X[1].length?0:parseInt(X[1],10),0==Sa[1].length?0:parseInt(Sa[1],10))||uh(0==X[2].length,0==Sa[2].length)||uh(X[2],Sa[2])}while(0==b)}b=ji[a]=0<=b}return b},ki=v.document,li=ki&&G?
di()||(ki.compatMode==Fb?parseInt(ii,10):5):void 0;var mi=!G||9<=Number(li);!bi&&!G||G&&9<=Number(li)||bi&&H("1.9.1");G&&H("9");var pi=function(a){return a?new ni(oi(a)):hh||(hh=new ni)},I=function(a){return z(a)?document.getElementById(a):a},ri=function(a,b){Lh(b,function(b,d){d==og?a.style.cssText=b:d==Cd?a.className=b:d==re?a.htmlFor=b:qi.hasOwnProperty(d)?a.setAttribute(qi[d],b):0==d.lastIndexOf(id,0)||0==d.lastIndexOf(Nd,0)?a.setAttribute(d,b):a[d]=b})},qi={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:Xf,rowspan:"rowSpan",
type:"type",usemap:"useMap",valign:"vAlign",width:"width"},ti=function(a,b,c){return si(document,arguments)},si=function(a,b){var c=b[0],d=b[1];if(!mi&&d&&(d.name||d.type)){c=[rb,c];d.name&&c.push(da,th(d.name),ja);if(d.type){c.push(ha,th(d.type),ja);var f={};Sh(f,d);delete f.type;d=f}c.push(sb);c=c.join(e)}c=a.createElement(c);d&&(z(d)?c.className=d:y(d)?c.className=d.join(h):ri(c,d));2<b.length&&ui(a,c,b,2);return c},ui=function(a,b,c,d){function f(c){c&&b.appendChild(z(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var g=c[d];!Yg(g)||ah(g)&&0<g.nodeType?f(g):Bh(vi(g)?Jh(g):g,f)}},wi=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},oi=function(a){C(a,ic);return 9==a.nodeType?a:a.ownerDocument||a.document},vi=function(a){if(a&&typeof a.length==pf){if(ah(a))return typeof a.item==q||typeof a.item==ng;if($g(a))return typeof a.item==q}return!1},ni=function(a){this.ta=a||v.document||document};u=ni.prototype;u.rb=function(a){return z(a)?this.ta.getElementById(a):a};
u.Ad=function(a,b,c){c=c||this.ta;a=a&&a!=Ka?a.toUpperCase():e;if(c.querySelectorAll&&c.querySelector&&(a||b))b=c.querySelectorAll(a+(b?Oa+b:e));else if(b&&c.getElementsByClassName)if(c=c.getElementsByClassName(b),a){for(var d={},f=0,g=0,k;k=c[g];g++)a==k.nodeName&&(d[f++]=k);d.length=f;b=d}else b=c;else if(c=c.getElementsByTagName(a||Ka),b){d={};for(g=f=0;k=c[g];g++)a=k.className,typeof a.split==q&&E(a.split(/\s+/),b)&&(d[f++]=k);d.length=f;b=d}else b=c;return b};
u.dc=function(a,b,c){return si(this.ta,arguments)};u.createElement=function(a){return this.ta.createElement(a)};u.createTextNode=function(a){return this.ta.createTextNode(String(a))};u.appendChild=function(a,b){a.appendChild(b)};u.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var J=function(){this.sa=this.sa;this.Hb=this.Hb};J.prototype.sa=!1;J.prototype.la=function(){this.sa||(this.sa=!0,this.l())};J.prototype.l=function(){if(this.Hb)for(;this.Hb.length;)this.Hb.shift()()};var xi=function(a){a&&typeof a.la==q&&a.la()};var K=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.pa=!1;this.re=!0};K.prototype.stopPropagation=function(){this.pa=!0};K.prototype.preventDefault=function(){this.defaultPrevented=!0;this.re=!1};var yi=function(a){yi[h](a);return a};yi[h]=Vg;var zi=!G||9<=Number(li),Ai=G&&!H("9");!ci||H("528");bi&&H("1.9b")||G&&H("8")||$h&&H("9.5")||ci&&H("528");bi&&!H("8")||G&&H("9");var L=function(a,b){K.call(this,a?a.type:e);this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.La=this.state=null;a&&this.Nd(a,b)};B(L,K);
L.prototype.Nd=function(a,b){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var f=a.relatedTarget;if(f){if(bi){var g;a:{try{yi(f.nodeName);g=!0;break a}catch(k){}g=!1}g||(f=null)}}else c==ff?f=a.fromElement:c==ef&&(f=a.toElement);this.relatedTarget=f;null===d?(this.offsetX=ci||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=ci||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=
void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c==Ye?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.La=a;a.defaultPrevented&&this.preventDefault()};
L.prototype.stopPropagation=function(){L.h.stopPropagation.call(this);this.La.stopPropagation?this.La.stopPropagation():this.La.cancelBubble=!0};L.prototype.preventDefault=function(){L.h.preventDefault.call(this);var a=this.La;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ai)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Bi="closure_listenable_"+(1E6*Math.random()|0),Ci=function(a){return!(!a||!a[Bi])},Di=0;var Ei=function(a,b,c,d,f,g){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.ib=!!f;this.vb=g;this.key=++Di;this.Ba=this.hb=!1};Ei.prototype.Fb=function(){this.Ba=!0;this.vb=this.src=this.proxy=this.listener=null};var Fi=function(a){this.src=a;this.o={};this.ab=0};u=Fi.prototype;u.add=function(a,b,c,d,f){var g=a.toString();a=this.o[g];a||(a=this.o[g]=[],this.ab++);var k=Gi(a,b,d,f);-1<k?(b=a[k],c||(b.hb=!1)):(b=new Ei(b,null,this.src,g,!!d,f),b.hb=c,a.push(b));return b};u.remove=function(a,b,c,d){a=a.toString();if(!(a in this.o))return!1;var f=this.o[a];b=Gi(f,b,c,d);return-1<b?(f[b].Fb(),Gh(f,b),0==f.length&&(delete this.o[a],this.ab--),!0):!1};
u.ne=function(a){var b=a.type;if(!(b in this.o))return!1;var c=Hh(this.o[b],a);c&&(a.Fb(),0==this.o[b].length&&(delete this.o[b],this.ab--));return c};u.Jb=function(a){a=a&&a.toString();var b=0,c;for(c in this.o)if(!a||c==a){for(var d=this.o[c],f=0;f<d.length;f++)++b,d[f].Fb();delete this.o[c];this.ab--}return b};u.Ma=function(a,b,c,d){a=this.o[a.toString()];var f=-1;a&&(f=Gi(a,b,c,d));return-1<f?a[f]:null};
var Gi=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.Ba&&g.listener==b&&g.ib==!!c&&g.vb==d)return f}return-1};var Hi="closure_lm_"+(1E6*Math.random()|0),Ii={},Ji=0,M=function(a,b,c,d,f){if(y(b)){for(var g=0;g<b.length;g++)M(a,b[g],c,d,f);return null}c=Ki(c);return Ci(a)?a.Aa(b,c,d,f):Li(a,b,c,!1,d,f)},Li=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var k=!!f,m=Mi(a);m||(a[Hi]=m=new Fi(a));c=m.add(b,c,d,f,g);if(c.proxy)return c;d=Ni();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,k);else if(a.attachEvent)a.attachEvent(Oi(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");
Ji++;return c},Ni=function(){var a=Pi,b=zi?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Qi=function(a,b,c,d,f){if(y(b)){for(var g=0;g<b.length;g++)Qi(a,b[g],c,d,f);return null}c=Ki(c);return Ci(a)?a.uc(b,c,d,f):Li(a,b,c,!0,d,f)},Ri=function(a,b,c,d,f){if(y(b)){for(var g=0;g<b.length;g++)Ri(a,b[g],c,d,f);return null}c=Ki(c);if(Ci(a))return a.Ob(b,c,d,f);if(!a)return!1;if(a=Mi(a))if(b=a.Ma(b,c,!!d,f))return Si(b);return!1},Si=function(a){if(Zg(a)||
!a||a.Ba)return!1;var b=a.src;if(Ci(b))return b.Je(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.ib):b.detachEvent&&b.detachEvent(Oi(c),d);Ji--;(c=Mi(b))?(c.ne(a),0==c.ab&&(c.src=null,b[Hi]=null)):a.Fb();return!0},Ti=function(a,b){if(!a)return 0;if(Ci(a))return a.me(b);var c=Mi(a);if(!c)return 0;var d=0,f=b&&b.toString(),g;for(g in c.o)if(!f||g==f)for(var k=c.o[g].concat(),m=0;m<k.length;++m)Si(k[m])&&++d;return d},Oi=function(a){return a in Ii?Ii[a]:Ii[a]=tf+a},Vi=function(a,
b,c,d){var f=!0;if(a=Mi(a))if(b=a.o[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.ib==c&&!g.Ba&&(g=Ui(g,d),f=f&&!1!==g)}return f},Ui=function(a,b){var c=a.listener,d=a.vb||a.src;a.hb&&Si(a);return c.call(d,b)},Pi=function(a,b){if(a.Ba)return!0;if(!zi){var c;if(!(c=b))a:{c=[Pg,je];for(var d=v,f;f=c.shift();)if(null!=d[f])d=d[f];else{c=null;break a}c=d}f=c;c=new L(f,this);d=!0;if(!(0>f.keyCode||void 0!=f.returnValue)){a:{var g=!1;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(r){g=
!0}if(g||void 0==f.returnValue)f.returnValue=!0}f=[];for(g=c.currentTarget;g;g=g.parentNode)f.push(g);for(var g=a.type,k=f.length-1;!c.pa&&0<=k;k--){c.currentTarget=f[k];var m=Vi(f[k],g,!0,c),d=d&&m}for(k=0;!c.pa&&k<f.length;k++)c.currentTarget=f[k],m=Vi(f[k],g,!1,c),d=d&&m}return d}return Ui(a,new L(b,this))},Mi=function(a){a=a[Hi];return a instanceof Fi?a:null},Wi="__closure_events_fn_"+(1E9*Math.random()>>>0),Ki=function(a){C(a,Vb);if($g(a))return a;C(a.handleEvent,Bb);a[Wi]||(a[Wi]=function(b){return a.handleEvent(b)});
return a[Wi]};var N=function(){J.call(this);this.V=new Fi(this);this.xf=this;this.Bc=null};B(N,J);N.prototype[Bi]=!0;u=N.prototype;u.addEventListener=function(a,b,c,d){M(this,a,b,c,d)};u.removeEventListener=function(a,b,c,d){Ri(this,a,b,c,d)};
u.dispatchEvent=function(a){this.gd();var b,c=this.Bc;if(c){b=[];for(var d=1;c;c=c.Bc)b.push(c),C(1E3>++d,Ue)}c=this.xf;d=a.type||a;if(z(a))a=new K(a,c);else if(a instanceof K)a.target=a.target||c;else{var f=a;a=new K(d,c);Sh(a,f)}var f=!0,g;if(b)for(var k=b.length-1;!a.pa&&0<=k;k--)g=a.currentTarget=b[k],f=g.pb(d,!0,a)&&f;a.pa||(g=a.currentTarget=c,f=g.pb(d,!0,a)&&f,a.pa||(f=g.pb(d,!1,a)&&f));if(b)for(k=0;!a.pa&&k<b.length;k++)g=a.currentTarget=b[k],f=g.pb(d,!1,a)&&f;return f};
u.l=function(){N.h.l.call(this);this.me();this.Bc=null};u.Aa=function(a,b,c,d){this.gd();return this.V.add(String(a),b,!1,c,d)};u.uc=function(a,b,c,d){return this.V.add(String(a),b,!0,c,d)};u.Ob=function(a,b,c,d){return this.V.remove(String(a),b,c,d)};u.Je=function(a){return this.V.ne(a)};u.me=function(a){return this.V?this.V.Jb(a):0};
u.pb=function(a,b,c){a=this.V.o[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.Ba&&g.ib==b){var k=g.listener,m=g.vb||g.src;g.hb&&this.Je(g);d=!1!==k.call(m,c)&&d}}return d&&0!=c.re};u.Ma=function(a,b,c,d){return this.V.Ma(String(a),b,c,d)};u.gd=function(){C(this.V,Lb)};var Xi=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,vb).replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,Gc).replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e)))try{return eval(Ha+a+Ja)}catch(b){}throw Error("Invalid JSON string: "+a);};var Yi=function(a){return a};var Zi="StopIteration"in v?v.StopIteration:{message:"StopIteration",stack:e},$i=function(){};$i.prototype.next=function(){throw Zi;};$i.prototype.Yb=function(){return this};var aj=function(a,b){this.j={};this.c=[];this.bb=this.b=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};u=aj.prototype;u.s=function(){return this.b};u.u=function(){this.lb();for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};u.K=function(){this.lb();return this.c.concat()};u.ka=function(a){return bj(this.j,a)};u.isEmpty=function(){return 0==this.b};
u.clear=function(){this.j={};this.bb=this.b=this.c.length=0};u.remove=function(a){return bj(this.j,a)?(delete this.j[a],this.b--,this.bb++,this.c.length>2*this.b&&this.lb(),!0):!1};u.lb=function(){if(this.b!=this.c.length){for(var a=0,b=0;a<this.c.length;){var c=this.c[a];bj(this.j,c)&&(this.c[b++]=c);a++}this.c.length=b}if(this.b!=this.c.length){for(var d={},b=a=0;a<this.c.length;)c=this.c[a],bj(d,c)||(this.c[b++]=c,d[c]=1),a++;this.c.length=b}};
u.get=function(a,b){return bj(this.j,a)?this.j[a]:b};u.set=function(a,b){bj(this.j,a)||(this.b++,this.c.push(a),this.bb++);this.j[a]=b};u.addAll=function(a){var b;a instanceof aj?(b=a.K(),a=a.u()):(b=Nh(a),a=Mh(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};u.forEach=function(a,b){for(var c=this.K(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};u.clone=function(){return new aj(this)};
u.Yb=function(a){this.lb();var b=0,c=this.bb,d=this,f=new $i;f.next=function(){if(c!=d.bb)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw Zi;var f=d.c[b++];return a?f:d.j[f]};return f};var bj=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var cj=function(a){if(a.u&&typeof a.u==q)return a.u();if(z(a))return a.split(e);if(Yg(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Mh(a)},dj=function(a,b,c){if(a.forEach&&typeof a.forEach==q)a.forEach(b,c);else if(Yg(a)||z(a))Bh(a,b,c);else{var d;if(a.K&&typeof a.K==q)d=a.K();else if(a.u&&typeof a.u==q)d=void 0;else if(Yg(a)||z(a)){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g)}else d=Nh(a);for(var f=cj(a),g=f.length,k=0;k<g;k++)b.call(c,f[k],d&&d[k],a)}};var ej=function(a){this.j=new aj;a&&this.addAll(a)},fj=function(a){var b=typeof a;return b==rf&&a||b==q?qf+(a[bh]||(a[bh]=++ch)):b.substr(0,1)+a};u=ej.prototype;u.s=function(){return this.j.s()};u.add=function(a){this.j.set(fj(a),a)};u.addAll=function(a){a=cj(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};u.Jb=function(a){a=cj(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};u.remove=function(a){return this.j.remove(fj(a))};u.clear=function(){this.j.clear()};u.isEmpty=function(){return this.j.isEmpty()};
u.contains=function(a){return this.j.ka(fj(a))};u.u=function(){return this.j.u()};u.clone=function(){return new ej(this)};u.Yb=function(){return this.j.Yb(!1)};var gj=function(a,b,c){if($g(a))c&&(a=A(a,c));else if(a&&typeof a.handleEvent==q)a=A(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:v.setTimeout(a,b||0)};var hj=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,ij=function(a,b){if(a)for(var c=a.split(l),d=0;d<c.length;d++){var f=c[d].indexOf(n),g=null,k=null;0<=f?(g=c[d].substring(0,f),k=c[d].substring(f+1)):g=c[d];b(g,k?decodeURIComponent(k.replace(/\+/g,h)):e)}};var jj=function(){};jj.prototype.md=null;jj.prototype.Fd=function(){return this.md||(this.md=this.wg())};var kj,lj=function(){};B(lj,jj);lj.prototype.qd=function(){var a=this.Gd();return a?new ActiveXObject(a):new XMLHttpRequest};lj.prototype.wg=function(){var a={};this.Gd()&&(a[0]=!0,a[1]=!0);return a};
lj.prototype.Gd=function(){if(!this.Ld&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=[$b,Zb,Yb,bc],b=0;b<a.length;b++){var c=a[b];try{return new ActiveXObject(c),this.Ld=c}catch(d){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return this.Ld};kj=new lj;var O=function(a){N.call(this);this.headers=new aj;this.Tb=a||null;this.aa=!1;this.Sb=this.a=null;this.tc=e;this.za=0;this.na=this.qc=this.yb=this.ic=!1;this.qa=0;this.Nb=null;this.Ca=e;this.Nc=this.hh=this.Fa=!1};B(O,N);var mj=/^https?$/i,nj=[lc,"PUT"],oj=[],pj=function(a,b,c,d,f,g,k){var m=new O;oj.push(m);b&&m.Aa(p,b);m.uc(Rf,m.If);g&&m.Ic(g);k&&m.Jc(k);m.send(a,c,d,f);return m};u=O.prototype;u.If=function(){this.la();Hh(oj,this)};u.Ic=function(a){this.qa=Math.max(0,a)};
u.ph=function(a){this.Ca=a};u.Jc=function(a){this.Fa=a};
u.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.tc+"; newUri="+a);b=b?b.toUpperCase():Pb;this.tc=a;this.za=0;this.ic=!1;this.aa=!0;this.a=this.Mf();this.Sb=this.Tb?this.Tb.Fd():kj.Fd();this.a.onreadystatechange=A(this.he,this);this.hh&&vf in this.a&&(this.a.onprogress=A(function(a){this.fe(a,!0)},this),this.a.upload&&(this.a.upload.onprogress=A(this.fe,this)));try{this.qc=!0,this.a.open(b,String(a),!0),this.qc=!1}catch(g){this.yd(5,g);
return}a=c||e;var f=this.headers.clone();d&&dj(d,function(a,b){f.set(b,a)});d=Eh(f.K(),qj);c=v.FormData&&a instanceof v.FormData;!E(nj,b)||d||c||f.set(Jb,hd);f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Ca&&(this.a.responseType=this.Ca);Oh(this.a,Qg)&&(this.a.withCredentials=this.Fa);try{this.nd(),0<this.qa&&((this.Nc=rj(this.a))?(this.a.timeout=this.qa,this.a.ontimeout=A(this.He,this)):this.Nb=gj(this.He,this.qa,this)),this.yb=!0,this.a.send(a),this.yb=!1}catch(g){this.yd(5,g)}};
var rj=function(a){return G&&H(9)&&Zg(a.timeout)&&w(a.ontimeout)},qj=function(a){return Md==a.toLowerCase()};u=O.prototype;u.Mf=function(){return this.Tb?this.Tb.qd():kj.qd()};u.He=function(){"undefined"!=typeof Ug&&this.a&&(this.za=8,this.dispatchEvent(wg),this.abort(8))};u.yd=function(a){this.aa=!1;this.a&&(this.na=!0,this.a.abort(),this.na=!1);this.za=a;this.vd();this.kb()};u.vd=function(){this.ic||(this.ic=!0,this.dispatchEvent(p),this.dispatchEvent(ee))};
u.abort=function(a){this.a&&this.aa&&(this.aa=!1,this.na=!0,this.a.abort(),this.na=!1,this.za=a||7,this.dispatchEvent(p),this.dispatchEvent(Wc),this.kb())};u.l=function(){this.a&&(this.aa&&(this.aa=!1,this.na=!0,this.a.abort(),this.na=!1),this.kb(!0));O.h.l.call(this)};u.he=function(){this.sa||(this.qc||this.yb||this.na?this.ge():this.ah())};u.ah=function(){this.ge()};
u.ge=function(){if(this.aa&&"undefined"!=typeof Ug&&(!this.Sb[1]||4!=this.tb()||2!=this.getStatus()))if(this.yb&&4==this.tb())gj(this.he,0,this);else if(this.dispatchEvent(Sf),this.yg()){this.aa=!1;try{this.Sa()?(this.dispatchEvent(p),this.dispatchEvent(rg)):(this.za=6,this.vd())}finally{this.kb()}}};u.fe=function(a,b){C(a.type===Of,Be);this.dispatchEvent(sj(a,Of));this.dispatchEvent(sj(a,b?Yd:Ag))};var sj=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}};
u=O.prototype;u.kb=function(a){if(this.a){this.nd();var b=this.a,c=this.Sb[0]?Vg:null;this.Sb=this.a=null;a||this.dispatchEvent(Rf);try{b.onreadystatechange=c}catch(d){}}};u.nd=function(){this.a&&this.Nc&&(this.a.ontimeout=null);Zg(this.Nb)&&(v.clearTimeout(this.Nb),this.Nb=null)};u.Ab=function(){return!!this.a};u.yg=function(){return 4==this.tb()};
u.Sa=function(){var a=this.getStatus(),b;a:switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:b=!0;break a;default:b=!1}return b||0===a&&!this.zg()};u.zg=function(){var a=String(this.tc).match(hj)[1]||null;!a&&v.self&&v.self.location&&(a=v.self.location.protocol,a=a.substr(0,a.length-1));return mj.test(a?a.toLowerCase():e)};u.tb=function(){return this.a?this.a.readyState:0};u.getStatus=function(){try{return 2<this.tb()?this.a.status:-1}catch(a){return-1}};
u.eg=function(){try{return this.a?this.a.responseText:e}catch(a){return e}};u.Hd=function(a){if(this.a){var b=this.a.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));return Xi(b)}};u.dg=function(){try{if(!this.a)return null;if(Uf in this.a)return this.a.response;switch(this.Ca){case e:case tg:return this.a.responseText;case ld:if(gf in this.a)return this.a.mozResponseArrayBuffer}return null}catch(a){return null}};var tj=function(){};tj.prototype.R=function(){return dc};tj.prototype.L=function(){return null};var uj=function(a){this.label=a};B(uj,tj);uj.prototype.A=function(){return this.label};var P=function(a,b){this.label=b;this.value=a.R();this.X=a};B(P,tj);P.prototype.A=function(){return this.label};P.prototype.R=function(){return this.value};P.prototype.encode=function(){return this.X.encode()+n};P.prototype.L=function(){return new vj(this)};var Q=function(){};B(Q,tj);Q.prototype.encode=function(){return encodeURIComponent(this.R())};Q.prototype.L=function(){return null};var wj=function(a){P.call(this,a,a.A())};B(wj,P);var xj=function(){};B(xj,Q);xj.prototype.A=function(){return Cb};xj.prototype.R=function(){return yb};xj.prototype.decode=function(){return new wj(this)};var yj=function(a,b){this.mb=this.Oc=this.Da=e;this.Ib=null;this.qb=this.je=e;this.G=this.Ag=!1;var c;a instanceof yj?(this.G=w(b)?b:a.G,this.Be(a.Da),this.Fe(a.Oc),this.ve(a.mb),this.ze(a.Ib),this.setPath(a.getPath()),this.Ae(a.fa.clone()),this.xe(a.qb)):a&&(c=String(a).match(hj))?(this.G=!!b,this.Be(c[1]||e,!0),this.Fe(c[2]||e,!0),this.ve(c[3]||e,!0),this.ze(c[4]),this.setPath(c[5]||e,!0),this.Ae(c[6]||e,!0),this.xe(c[7]||e,!0)):(this.G=!!b,this.fa=new zj(null,null,this.G))};u=yj.prototype;
u.toString=function(){var a=[],b=this.Da;b&&a.push(Aj(b,Bj,!0),nb);var c=this.mb;if(c||b==oe)a.push(Xa),(b=this.Oc)&&a.push(Aj(b,Bj,!0),vb),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,pa)),c=this.Ib,null!=c&&a.push(nb,String(c));if(c=this.getPath())this.og()&&c.charAt(0)!=Wa&&a.push(Wa),a.push(Aj(c,c.charAt(0)==Wa?Cj:Dj,!0));(c=this.Xf())&&a.push(tb,c);(c=this.qb)&&a.push(la,Aj(c,Ej));return a.join(e)};u.clone=function(){return new yj(this)};
u.Be=function(a,b){this.da();if(this.Da=b?Fj(a,!0):a)this.Da=this.Da.replace(/:$/,e);return this};u.Fe=function(a,b){this.da();this.Oc=b?Fj(a):a;return this};u.ve=function(a,b){this.da();this.mb=b?Fj(a,!0):a;return this};u.og=function(){return!!this.mb};u.ze=function(a){this.da();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.Ib=a}else this.Ib=null;return this};u.getPath=function(){return this.je};u.setPath=function(a,b){this.da();this.je=b?Fj(a,!0):a;return this};
u.Ae=function(a,b){this.da();a instanceof zj?(this.fa=a,this.fa.Hc(this.G)):(b||(a=Aj(a,Gj)),this.fa=new zj(a,null,this.G));return this};u.Xf=function(){return this.fa.toString()};u.Mb=function(a,b){this.da();this.fa.set(a,b);return this};u.xe=function(a,b){this.da();this.qb=b?Fj(a):a;return this};u.da=function(){if(this.Ag)throw Error("Tried to modify a read-only Uri");};u.Hc=function(a){this.G=a;this.fa&&this.fa.Hc(a);return this};
var Fj=function(a,b){return a?b?decodeURI(a.replace(/%25/g,qa)):decodeURIComponent(a):e},Aj=function(a,b,c){return z(a)?(a=encodeURI(a).replace(b,Hj),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,pa)),a):null},Hj=function(a){a=a.charCodeAt(0);return oa+(a>>4&15).toString(16)+(a&15).toString(16)},Bj=/[#\/\?@]/g,Dj=/[\#\?:]/g,Cj=/[\#\?]/g,Gj=/[\#\?@]/g,Ej=/#/g,zj=function(a,b,c){this.b=this.g=null;this.ca=a||null;this.G=!!c};u=zj.prototype;
u.U=function(){if(!this.g&&(this.g=new aj,this.b=0,this.ca)){var a=this;ij(this.ca,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,h)),c)})}};u.s=function(){this.U();return this.b};u.add=function(a,b){this.U();this.ya();a=this.va(a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.b=D(this.b)+1;return this};u.remove=function(a){this.U();a=this.va(a);return this.g.ka(a)?(this.ya(),this.b=D(this.b)-this.g.get(a).length,this.g.remove(a)):!1};
u.clear=function(){this.ya();this.g=null;this.b=0};u.isEmpty=function(){this.U();return 0==this.b};u.ka=function(a){this.U();a=this.va(a);return this.g.ka(a)};u.K=function(){this.U();for(var a=this.g.u(),b=this.g.K(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};u.u=function(a){this.U();var b=[];if(z(a))this.ka(a)&&(b=Ih(b,this.g.get(this.va(a))));else{a=this.g.u();for(var c=0;c<a.length;c++)b=Ih(b,a[c])}return b};
u.set=function(a,b){this.U();this.ya();a=this.va(a);this.ka(a)&&(this.b=D(this.b)-this.g.get(a).length);this.g.set(a,[b]);this.b=D(this.b)+1;return this};u.get=function(a,b){var c=a?this.u(a):[];return 0<c.length?String(c[0]):b};u.setValues=function(a,b){this.remove(a);0<b.length&&(this.ya(),this.g.set(this.va(a),Jh(b)),this.b=D(this.b)+b.length)};
u.toString=function(){if(this.ca)return this.ca;if(!this.g)return e;for(var a=[],b=this.g.K(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.u(d),g=0;g<d.length;g++){var k=f;d[g]!==e&&(k+=n+encodeURIComponent(String(d[g])));a.push(k)}return this.ca=a.join(l)};u.ya=function(){this.ca=null};u.clone=function(){var a=new zj;a.ca=this.ca;this.g&&(a.g=this.g.clone(),a.b=this.b);return a};u.va=function(a){a=String(a);this.G&&(a=a.toLowerCase());return a};
u.Hc=function(a){a&&!this.G&&(this.U(),this.ya(),this.g.forEach(function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.setValues(d,a))},this));this.G=a};var Ij=e;var Jj=function(a){if(a.classList)return a.classList;a=a.className;return z(a)&&a.match(/\S+/g)||[]},Kj=function(a,b){return a.classList?a.classList.contains(b):E(Jj(a),b)},Lj=function(a,b){a.classList?a.classList.add(b):Kj(a,b)||(a.className+=0<a.className.length?h+b:b)},Mj=function(a,b){a.classList?a.classList.remove(b):Kj(a,b)&&(a.className=Ch(Jj(a),function(a){return a!=b}).join(h))};var Nj=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=ci&&!b&&!c;if((!w(b)||d)&&a.getBoundingClientRect){var f;a:{try{f=a.getBoundingClientRect()}catch(g){f={left:0,top:0,right:0,bottom:0};break a}G&&a.ownerDocument.body&&(a=a.ownerDocument,f.left-=a.documentElement.clientLeft+a.body.clientLeft,f.top-=a.documentElement.clientTop+a.body.clientTop)}return new Zh(f.right-f.left,f.bottom-f.top)}return new Zh(b,c)},Pj=function(a,b){var c=pi(b),d=null,f=c.ta;G&&f.createStyleSheet?(d=f.createStyleSheet(),
Oj(d,a)):(f=c.Ad(Sb)[0],f||(d=c.Ad(Eb)[0],f=c.dc(Sb),d.parentNode.insertBefore(f,d)),d=c.dc(pc),Oj(d,a),c.appendChild(f,d));return d},Oj=function(a,b){var c;b instanceof Wh&&b.constructor===Wh&&b.hf===Vh?c=b.Ec:(xh(le+b+Ga+Xg(b)),c=zg);if(G&&w(a.cssText))a.cssText=c;else if(C(null!=a,Ae),vg in a)a.textContent=c;else if(3==a.nodeType)a.data=c;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=c}else{wi(a);var d=oi(a);a.appendChild(d.createTextNode(String(c)))}};/*

 CC0 1.0 Universal License
 Public Domain Dedication

 The person(s) who associated a work with this deed has dedicated the work to
 the public domain by waiving all of his or her rights to the work worldwide
 under copyright law, including all related and neighboring rights, to the
 extent allowed by law.

 You can copy, modify, distribute and perform the work, even for commercial
 purposes, all without asking permission.

 In no way are the patent or trademark rights of any person affected by CC0,
 nor are the rights that other persons may have in the work or in how the work
 is used, such as publicity or privacy rights.

 Unless expressly stated otherwise, the person(s) who associated a work with
 this deed makes no warranties about the work, and disclaims liability for all
 uses of the work, to the fullest extent permitted by applicable law.

 When using or citing the work, you should not imply endorsement by the author
 or the affirmer.

 This is a human-readable summary of the Legal Code (read the full text).
*/
var Qj=function(a){function b(a,b){if(b){var c=document.createDocumentFragment(),k=!a.getAttribute(Fg)&&b.getAttribute(Fg);k&&a.setAttribute(Fg,k);for(k=b.cloneNode(!0);k.childNodes.length;)c.appendChild(k.firstChild);a.appendChild(c)}}function c(a){a.onreadystatechange=function(){if(4===a.readyState){var c=a.wf;c||(c=a.wf=document.implementation.createHTMLDocument(e),c.body.innerHTML=a.responseText,a.ad={});a.bd.splice(0).map(function(g){var k=a.ad[g.id];k||(k=a.ad[g.id]=c.getElementById(g.id));
b(g.th,k)})}};a.onreadystatechange()}(function(a){function f(){for(var a=0;a<X.length;){var d=X[a],m=d.parentNode;if(m&&/svg/i.test(m.nodeName)){var r=d.getAttribute(Rg);if(g&&(!k.wh||k.wh(r,m,d)))if(m.removeChild(d),r=r.split(la),d=r.shift(),r=r.join(la),d.length){var fa=ta[d];fa||(fa=ta[d]=new XMLHttpRequest,fa.open(Pb,d),fa.send(),fa.bd=[]);fa.bd.push({th:m,id:r});c(fa)}else b(m,document.getElementById(r))}else++a}window.requestAnimationFrame&&window.requestAnimationFrame(f)||setTimeout(f,67)}
var g,k=Object(a);a=/\bTrident\/[567]\b|\bMSIE (?:9|10)\.0\b/;var m=/\bAppleWebKit\/(\d+)\b/,r=/\bEdge\/12\.(\d+)\b/;g=Jf in k?k.rj:a.test(navigator.userAgent)||10547>(navigator.userAgent.match(r)||[])[1]||537>(navigator.userAgent.match(m)||[])[1];var ta={},X=document.getElementsByTagName(Bg);g&&f()})(a)};var Rj=function(a){return/^[A-Za-z0-9]+$/.test(a)||/^#[0-9A-Fa-f]{3}$/.test(a)||/^#[0-9A-Fa-f]{6}$/.test(a)||/^rgb *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)||/^rgba *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)},Sj=function(a){a=a.split(La);for(var b=0;b<a.length;b++){var c=a[b],c=lh(c);if(!(/^[- A-Za-z0-9]*$/.test(c)||/^"[- A-Za-z0-9]*"$/.test(c)||/^'[- A-Za-z0-9]*'$/.test(c)))return!1}return!0},Tj=function(){if(window.parent&&window.parent.postMessage){var a=
document.getElementById(Mf),b=0;if(a){b:{b=oi(a);if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue(Sd)||e;break b}b=e}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display)!=t)a=Nj(a);else{var b=a.style,c=b.display,d=b.visibility,f=b.position;b.visibility=Ce;b.position=Xc;b.display=Ve;a=Nj(a);b.display=c;b.position=f;b.visibility=d}b=a.height}b=Math.max(b,document.body.scrollHeight);window.parent.postMessage(eg+
(b||230)+Pf,Ka)}},Uj=function(){var a=document.getElementById(Fd),b=document.getElementById(Lf),c=document.getElementById(Kf),d=function(){b&&(b.disabled=a.value==e);c&&(c.disabled=a.value==e)};a&&uf in a&&(d(null),M(a,We,d))},Vj=function(a){var b=e;G&&(b+=Ta);a=(new yj(a)).qb;if(0!=a.length){a=decodeURIComponent(a);var c=Xi(a);if(c&&c.color){a=kh(jh(c.color));var d=kh(jh(c.unvisitedLinkColor)),c=kh(jh(c.fontFamily));Rj(a)&&Rj(d)&&Sj(c)&&(b=b+(td+a+pb+c+qb)+(Vc+d+qb))}}Pj(Yh(b),void 0);setTimeout(Tj,
100);var f=I(cd);if((b=I(Fd))&&f){var g=!1;M(b,qe,function(){g||(g=!0,Mj(f,Jd),Tj())})}Qj()};var R=function(a){a=I(a);var b=a.nodeName.toLowerCase();a.style.display=b==ig||b==Te||b==Uc||b==We||b==bg?Ve:pd},S=function(a){I(a).style.display=t};var T=function(a,b,c){var d;c&&S(df);switch(a){case 0:a=d=wd;break;case 1:a=d=Le;break;case 2:case 3:case 4:a=af;d=bf;break;case 5:a=d=jf;break;case 6:a=d=wf;break;case 7:a=d=ue;break;default:throw Error("internal error in show message");}c?(I(a).innerHTML=b,R(d),I(Fd).className=Ed):(wi(I(a)),S(d));Tj()},Wj=function(a){T(3,null,!1);I(cf).innerHTML=a;R(df);Tj()};var Xj=function(){};Xj.prototype.sh=function(){S(Pe);I(Fd).disabled=!0;I(Lf).disabled=!0};Xj.prototype.pg=function(){R(Pe);I(Fd).disabled=!1;I(Lf).disabled=!1};var vj=function(a){this.m=a};B(vj,Xj);u=vj.prototype;u.oa=function(){return!1};u.ga=function(){if(!this.oa())throw Error("Trying to show a non-editable identity");this.sh();R(Oe)};u.Cb=function(){return!0};u.Kc=function(){if(!this.oa())throw Error("Trying to show edit button for a non-editable identity");R($d)};u.Va=function(){};u.Ya=function(){};u.Z=function(){S(Oe);S($d);S(fg);S(Gd);S(qg);this.pg()};var Yj=function(a){a=a.className;return z(a)&&a.match(/\S+/g)||[]},Zj=function(a,b){for(var c=Yj(a),d=Kh(arguments,1),f=c.length+d.length,g=c,k=0;k<d.length;k++)E(g,d[k])||g.push(d[k]);a.className=c.join(h);return c.length==f},bk=function(a,b){var c=Yj(a),d=Kh(arguments,1),f=ak(c,d);a.className=f.join(h);return f.length==c.length-d.length},ak=function(a,b){return Ch(a,function(a){return!E(b,a)})};var ek=function(a){for(var b=[],c=ck,d=a.elements,f,g=0;f=d[g];g++)if(f.form==a&&!f.disabled&&f.tagName!=Ob){var k=f.name;switch(f.type.toLowerCase()){case oe:case pg:case Tf:case ud:break;case cg:f=dk(f);if(null!=f)for(var m,r=0;m=f[r];r++)c(b,k,m);break;default:m=dk(f),null!=m&&c(b,k,m)}}d=a.getElementsByTagName(Tb);for(g=0;f=d[g];g++)f.form==a&&f.type.toLowerCase()==Re&&(k=f.name,c(b,k,f.value),c(b,k+Ua,ab),c(b,k+Va,ab));return b.join(l)},ck=function(a,b,c){a.push(encodeURIComponent(b)+n+encodeURIComponent(c))},
dk=function(a){var b=a.type;if(!w(b))return null;switch(b.toLowerCase()){case zd:case Qf:return a.checked?a.value:null;case dg:return b=a.selectedIndex,0<=b?a.options[b].value:null;case cg:for(var b=[],c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:null;default:return w(a.value)?a.value:null}};var fk=!1,gk=!1,hk=!1,ik=function(a,b){gk=a;hk=b;if(window.parent==window.top&&(a||b)){var c=I(qg);b?Zj(c,Ad):bk(c,Ad);R(qg);I(bd).value=b?yc:sc}else S(qg)};var kk=function(a,b){P.call(this,new jk,a);this.Wf=b};B(kk,P);kk.prototype.encode=function(){return this.X.encode()+n+this.label+n+this.Wf};kk.prototype.A=function(){return this.label+ca};kk.prototype.L=function(){return new lk(this)};var jk=function(){};B(jk,Q);jk.prototype.A=function(){return e};jk.prototype.R=function(){return Gb};jk.prototype.decode=function(a){return new kk(a[1],a[2])};jk.prototype.L=function(){throw Error("internal error");};var lk=function(a){this.m=a};B(lk,vj);
lk.prototype.Kc=function(){(gk||hk)&&R(qg)};var mk=function(a){P.call(this,a,a.A())};B(mk,P);var nk=function(){};B(nk,Q);nk.prototype.A=function(){return Rb};nk.prototype.R=function(){return Qb};nk.prototype.decode=function(){return this.Ed()};nk.prototype.Ed=function(){return new mk(this)};var ok=function(a,b,c){P.call(this,a,null);this.name=b;this.url=c};B(ok,P);ok.prototype.A=function(){return this.name+ba+this.url+Ja};ok.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.name)+n+encodeURIComponent(this.url)};ok.prototype.L=function(){return new pk(this)};var qk=function(){};B(qk,Q);qk.prototype.A=function(){return fc};qk.prototype.R=function(){return cc};qk.prototype.L=function(){return new pk(new ok(this,e,e))};
qk.prototype.decode=function(a){return new ok(this,a[1],a[2])};var pk=function(a){this.m=a};B(pk,vj);u=pk.prototype;u.oa=function(){return!0};u.ga=function(){pk.h.ga.call(this);R(kf)};u.Z=function(){pk.h.Z.call(this);S(kf);T(5,null,!1);this.ye(e);this.Ee(e)};u.Va=function(){this.ye(this.m.name);this.Ee(this.m.url)};u.Ya=function(){pk.h.Ya.call(this);this.m.name=this.Dd();this.m.url=this.hg();this.Kc()};u.Cb=function(){return this.Dd()==e?(T(5,ec,!0),!1):!0};u.Dd=function(){return I(fd).value};
u.ye=function(a){I(fd).value=a};u.hg=function(){return I(gd).value};u.Ee=function(a){I(gd).value=a};var rk=function(){this.ma=[];this.Ua=[];this.Ia=[];this.Pa=[];this.i=this.D=null;this.H=[]};u=rk.prototype;u.zb=function(a,b,c,d){for(var f=0;f<this.H.length;f++)if(a==this.H[f])return d(a);d=a.encode();for(f=0;f<this.H.length;f++)if(this.H[f].encode()==d)return c(this.H[f]);return b(a)};u.vg=function(a){return this.zb(a,A(function(a){return this.H[this.H.length]=a},this),Yi,Yi)};u.Bb=function(a){function b(){return!1}return this.zb(a,function(){return!0},b,b)};
u.Ra=function(a){function b(){throw Error("item should have been unique");}this.zb(a,Vg,b,b);return this.vg(a)};u.$b=function(a){return this.zb(a,A(function(a){this.H[this.H.length]=a;return this.ma[this.ma.length]=a},this),Yi,Yi)};u.$d=function(){for(var a=document.getElementById(Ne),b=Jj(a),c=0;c<b.length;c++)b[c].slice(0,14)==Me&&Mj(a,b[c]);(b=this.Pa[I(Pe).selectedIndex])&&Lj(a,Me+b.value)};u.ed=function(a){this.D=this.$b(a);this.Xa();this.Ha();this.gb(!1);return this.D};
u.ja=function(a){this.Ra(a);this.Ua[this.Ua.length]=a};u.Af=function(){var a=this.Ra(new nk);this.ja(a.Ed())};u.zf=function(){var a=new qk;this.Ra(a);this.Ia[this.Ia.length]=a};u.yf=function(){var a=this.Ra(new xj),a=this.Ra(new wj(a));this.Ia[this.Ia.length]=a};u.Ha=function(){var a=this.Pa[I(Pe).selectedIndex];a.constructor==uj?this.Xa():(T(1,null,!1),this.i=a.L(),null!=this.i&&this.i.Va(),this.$d())};
u.gb=function(a){if(null!=this.i){var b=this.i.m;if(a&&this.i.oa()&&this.Bb(b)||!this.i.Cb())this.i.ga();else return this.i.Ya(),this.i.Z(),this.i.oa()&&this.i.Kc(),this.i=null,b}return null};u.kh=function(){this.Nf(I(be).value);this.D=this.sd(I(ce).value);null==this.D&&0<this.ma.length&&(this.D=this.ma[0]);null==this.D&&1==this.Ua.length&&(this.D=this.Ua[0]);this.Xa();null!=this.D&&(this.Ha(),this.gb(!1))};
u.fd=function(a,b){this.Pa[this.Pa.length]=b;var c=document.createElement(Ef);c.text=b.A();c.value=b.R();try{a.add(c,null)}catch(d){a.add(c)}this.D==b&&(c.selected=!0);return c};u.ac=function(a,b){for(var c=0;c<b.length;c++)this.fd(a,b[c])};u.Xa=function(){for(var a=I(Pe);0!=a.options.length;)a.remove(0);this.Pa=[];this.fd(a,new uj(rc)).disabled=Rd;this.ac(a,this.ma);this.ac(a,this.Ua);this.ac(a,this.Ia)};u.Tf=function(){for(var a=[],b=0;b<this.ma.length;b++)a[a.length]=this.ma[b].encode();return a.join(l)};
u.Nf=function(a){if(a!=e){a=a.split(l);for(var b=0;b<a.length;b++)this.sd(a[b])}};u.sd=function(a){if(a==e)return null;a=a.split(n);for(var b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);b=this.Vf(a[0]);return null!=b?(a=b.decode(a),this.$b(a)):null};u.Vf=function(a){for(var b=0;b<this.H.length;b++)if(this.H[b].encode()==a)return this.H[b];return null};u.Me=function(){var a=I(Fd).value;if(a==e)return T(2,Hb,!0),!1;if(1E6<a.length)return T(2,Ib,!0),!1;T(2,null,!1);return!0};
u.zc=function(){null!=this.i&&this.i.Z();this.Ha();var a=this.gb(!0);null!=a&&(this.D=a)};u.Rg=function(){var a=this.gb(!1);null!=a&&this.ed(a)};u.Qg=function(){null!=this.i&&(this.i.Z(),this.i=null);this.Xa();this.zc()};u.ie=function(){if(null==this.D||this.D.R()==dc)return T(1,mc,!0),!1;if(null!=this.i)return!1;I(be).value=this.Tf();I(ce).value=this.D.encode();return!0};u.Tg=function(){this.D&&(this.Ha(),this.i.ga())};u.Zg=function(){this.Me()&&this.ie()&&this.wd(!1)};
u.$g=function(){this.Me()&&this.ie()&&this.wd(!0)};u.wd=function(a){I(gg).value=a?yg:ne;this.Ha();a=I(Hd);a.onsubmit();a.submit()};var sk=function(a,b,c,d){this.Of=a;this.Le=b;this.name=c;this.vh=d};B(sk,Q);u=sk.prototype;u.A=function(){return this.name};u.encode=function(){return encodeURIComponent(this.Of)};u.Jf=function(a){return this.Le.replace(/{username}/,encodeURIComponent(a))};u.gg=function(){return this.Le.split(Sg)};u.L=function(){return new tk(new uk(this,e,e))};u.decode=function(a){return new uk(this,a[1],a[2])};var uk=function(a,b,c){P.call(this,a,b);this.username=c;this.uri=b;this.value=jc};B(uk,P);
uk.prototype.A=function(){return this.username+ba+this.X.A()+Ja};uk.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.uri)+n+encodeURIComponent(this.username)};uk.prototype.L=function(){return new tk(this)};var tk=function(a){this.m=a};B(tk,vj);u=tk.prototype;u.oa=function(){return!0};u.ga=function(){tk.h.ga.call(this);R(xf);I(Df).innerHTML=this.m.X.vh;for(var a=I(Cf),b=A(function(){this.le()},this),c=[yd,Ye,Xe,Ze,sd,qe],d=0;d<c.length;d++)M(a,c[d],b)};
u.Z=function(){tk.h.Z.call(this);Ti(I(Cf));S(xf);T(6,null,!1);I(Bf).value=e};u.Va=function(){this.rh(this.m.username);I(Bf).value=this.m.X.Jf(this.m.username)};u.Ya=function(){this.m.username=this.jc();this.Va()};u.Cb=function(){return this.jc()==e?(T(6,vc,!0),!1):!0};u.le=function(){var a=this.m.X.gg(),b=this.jc(),b=b==e?Cg:encodeURIComponent(b);I(yf).innerHTML=a[0];I(Af).innerHTML=b;I(zf).innerHTML=a[1]};u.jc=function(){return I(Cf).value};u.rh=function(a){I(Cf).value=a;this.le()};var vk=function(){};
B(vk,Q);vk.prototype.A=function(){return kc};vk.prototype.R=function(){return jc};vk.prototype.decode=function(a){return new wk(this,a[1])};vk.prototype.L=function(){return new xk(new wk(this,e))};var wk=function(a,b){P.call(this,a,b);this.uri=b;this.value=jc};B(wk,P);wk.prototype.A=function(){return this.uri};wk.prototype.encode=function(){return this.X.encode()+n+encodeURIComponent(this.uri)};wk.prototype.L=function(){return new xk(this)};var xk=function(a){this.m=a};B(xk,vj);u=xk.prototype;
u.oa=function(){return!0};u.ga=function(){xk.h.ga.call(this);R(ve)};u.Z=function(){xk.h.Z.call(this);S(ve);T(7,null,!1);this.De(e)};u.Va=function(){this.De(this.m.uri)};u.Ya=function(){this.m.uri=this.Id()};u.Cb=function(){return this.Id()==e?(T(7,uc,!0),!1):!0};u.Id=function(){return I(Bf).value};u.De=function(a){I(Bf).value=a};var yk=function(){bk(I(cd),Nf);return!0};var zk=function(a,b,c){J.call(this);this.vc=a;this.xg=b||0;this.wa=c;this.Ff=A(this.Qf,this)};B(zk,J);u=zk.prototype;u.Na=0;u.l=function(){zk.h.l.call(this);this.stop();delete this.vc;delete this.wa};u.start=function(a){this.stop();this.Na=gj(this.Ff,w(a)?a:this.xg)};u.stop=function(){this.Ab()&&v.clearTimeout(this.Na);this.Na=0};u.Ab=function(){return 0!=this.Na};u.Qf=function(){this.Na=0;this.vc&&this.vc.call(this.wa)};var Ak={},Bk=null,Ck=function(a){a=a[bh]||(a[bh]=++ch);delete Ak[a];Qh(Ak)&&Bk&&Bk.stop()},Ek=function(){Bk||(Bk=new zk(function(){Dk(fh())},20));var a=Bk;a.Ab()||a.start()},Dk=function(a){Lh(Ak,function(b){b.Og(a)});Qh(Ak)||Ek()};var Fk=function(){N.call(this);this.Ea=0;this.endTime=this.startTime=null};B(Fk,N);u=Fk.prototype;u.qh=function(){this.Ea=1};u.Ce=function(){this.Ea=0};u.Rd=function(){return 1==this.Ea};u.Qd=function(){return-1==this.Ea};u.Sd=function(){return 0==this.Ea};u.Pg=function(){this.S(md)};u.ee=function(){this.S(de)};u.Vg=function(){this.S(pe)};u.Yg=function(){this.S(If)};u.bh=function(){this.S(Wf)};u.dh=function(){this.S(mg)};u.S=function(a){this.dispatchEvent(a)};var Gk=function(a,b,c,d){Fk.call(this);if(!y(a)||!y(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.$a=a;this.Uf=b;this.duration=c;this.dd=d;this.coords=[];this.progress=0;this.sc=null};B(Gk,Fk);u=Gk.prototype;
u.play=function(a){if(a||this.Sd())this.progress=0,this.coords=this.$a;else if(this.Rd())return!1;Ck(this);this.startTime=a=fh();this.Qd()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.sc=this.startTime;this.progress||this.Pg();this.Yg();this.Qd()&&this.bh();this.qh();var b=this[bh]||(this[bh]=++ch);b in Ak||(Ak[b]=this);Ek();this.rd(a);return!0};u.stop=function(a){Ck(this);this.Ce();a&&(this.progress=1);this.Ke(this.progress);this.dh();this.ee()};
u.l=function(){this.Sd()||this.stop(!1);this.Sg();Gk.h.l.call(this)};u.Og=function(a){this.rd(a)};u.rd=function(a){D(this.startTime);D(this.endTime);D(this.sc);this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<=this.progress&&(this.progress=1);this.sc=a;this.Ke(this.progress);1==this.progress?(this.Ce(),Ck(this),this.Vg(),this.ee()):this.Rd()&&this.Lg()};
u.Ke=function(a){$g(this.dd)&&(a=this.dd(a));this.coords=Array(this.$a.length);for(var b=0;b<this.$a.length;b++)this.coords[b]=(this.Uf[b]-this.$a[b])*a+this.$a[b]};u.Lg=function(){this.S(ed)};u.Sg=function(){this.S(Qd)};u.S=function(a){this.dispatchEvent(new Hk(a,this))};var Hk=function(a,b){K.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.state=b.Ea};B(Hk,K);var Ik,Jk={yh:"activedescendant",Dh:"atomic",Eh:"autocomplete",Fh:"busy",Hh:Ad,Mh:"controls",Ph:"describedby",Sh:Rd,Uh:"dropeffect",Vh:ke,Wh:"flowto",Xh:"grabbed",ai:"haspopup",HIDDEN:Ce,di:"invalid",ei:"label",fi:"labelledby",gi:"level",li:"live",wi:"multiline",xi:"multiselectable",Ci:"orientation",Di:"owns",Ei:"posinset",Gi:"pressed",Ki:"readonly",Mi:"relevant",Ni:"required",Ti:"selected",Vi:"setsize",Xi:"sort",lj:"valuemax",mj:"valuemin",nj:"valuenow",oj:"valuetext"};var Kk={zh:"alert",Ah:"alertdialog",Bh:"application",Ch:"article",BANNER:"banner",BUTTON:ud,Gh:zd,Ih:"columnheader",Jh:"combobox",Kh:"complementary",Lh:"contentinfo",Oh:"definition",Qh:"dialog",Rh:"directory",Th:"document",FORM:se,Yh:"grid",Zh:"gridcell",$h:"group",bi:"heading",ci:Te,hi:"link",ii:"list",ji:"listbox",ki:"listitem",mi:"log",ni:"main",oi:"marquee",pi:"math",ri:"menu",si:"menubar",ti:"menuitem",ui:"menuitemcheckbox",vi:"menuitemradio",zi:"navigation",Ai:"note",Bi:Ef,Fi:"presentation",
Hi:"progressbar",Ii:Qf,Ji:"radiogroup",Li:"region",Oi:"row",Pi:"rowgroup",Qi:"rowheader",Ri:"scrollbar",Si:"search",Ui:"separator",Wi:"slider",Yi:"spinbutton",Zi:"status",aj:sg,bj:"tablist",cj:"tabpanel",dj:"textbox",ej:"textinfo",fj:"timer",gj:"toolbar",hj:"tooltip",ij:"tree",jj:"treegrid",kj:"treeitem"};var Lk=function(a){J.call(this);this.wa=a;this.c={}};B(Lk,J);var Mk=[];u=Lk.prototype;u.Aa=function(a,b,c,d){return this.Cg(a,b,c,d)};u.Cg=function(a,b,c,d,f){y(b)||(b&&(Mk[0]=b.toString()),b=Mk);for(var g=0;g<b.length;g++){var k=M(a,b[g],c||this.handleEvent,d||!1,f||this.wa||this);if(!k)break;this.c[k.key]=k}return this};u.uc=function(a,b,c,d){return this.Zd(a,b,c,d)};
u.Zd=function(a,b,c,d,f){if(y(b))for(var g=0;g<b.length;g++)this.Zd(a,b[g],c,d,f);else{a=Qi(a,b,c||this.handleEvent,d,f||this.wa||this);if(!a)return this;this.c[a.key]=a}return this};u.Ob=function(a,b,c,d,f){if(y(b))for(var g=0;g<b.length;g++)this.Ob(a,b[g],c,d,f);else c=c||this.handleEvent,f=f||this.wa||this,c=Ki(c),d=!!d,b=Ci(a)?a.Ma(b,c,d,f):a?(a=Mi(a))?a.Ma(b,c,d,f):null:null,b&&(Si(b),delete this.c[b.key]);return this};
u.Jb=function(){Lh(this.c,function(a,b){this.c.hasOwnProperty(b)&&Si(a)},this);this.c={}};u.l=function(){Lk.h.l.call(this);this.Jb()};u.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Nk=function(a,b,c,d,f){function g(a){a&&(a.tabIndex=0,C(Ph(Kk,sg),hc),a.setAttribute(Xf,sg),Lj(a,ze),k.Sf(a),k.Rf(a))}N.call(this);this.hc=f||pi();this.ba=this.hc.rb(a)||null;this.Ka=this.hc.rb(d||null);this.T=(this.Eb=$g(b)?b:null)||!b?null:this.hc.rb(b);this.W=1==c;w(c)||this.Eb||(this.Ka?this.W=this.Ka.style.display!=t:this.ba&&(this.W=Kj(this.ba,ye)));this.Yd=new Lk(this);this.ce=new Lk(this);var k=this;g(this.ba);g(this.Ka);this.Lb(this.W)};B(Nk,N);u=Nk.prototype;
u.l=function(){Nk.h.l.call(this);xi(this.Yd);xi(this.ce)};u.collapse=function(){this.Lb(!1)};u.toggle=function(){this.Lb(!this.W)};u.Lb=function(a){this.T?this.T.style.display=a?e:t:a&&this.Eb&&(this.T=this.Eb());this.T&&Lj(this.T,xe);this.Ka?(this.ba.style.display=a?t:e,this.Ka.style.display=a?e:t):this.Lc(a);this.we(a);this.dispatchEvent(new Ok(xg,this,this.W))};u.we=function(a){this.W=a};
u.Lc=function(a){if(this.ba){var b=this.ba;a?Lj(b,ye):Mj(b,ye);b=this.ba;a?Mj(b,we):Lj(b,we);b=this.ba;y(a)&&(a=a.join(h));C(ke,zb);C(Ph(Jk,ke),gc);a===e||void 0==a?(Ik||(Ik={atomic:!1,autocomplete:t,dropeffect:t,haspopup:!1,live:sf,multiline:!1,multiselectable:!1,orientation:Eg,readonly:!1,relevant:$c,required:!1,sort:t,busy:!1,disabled:!1,hidden:!1,invalid:ne}),a=Ik,ke in a?b.setAttribute(jd,a.expanded):b.removeAttribute(jd)):b.setAttribute(jd,a)}};u.Rf=function(a){a&&this.Yd.Aa(a,Xe,this.Xg)};
u.Sf=function(a){a&&this.ce.Aa(a,Dd,this.Wg)};u.Xg=function(a){if(13==a.keyCode||32==a.keyCode)this.toggle(),this.ud(),a.preventDefault(),a.stopPropagation()};u.Wg=function(){this.toggle();this.ud()};u.ud=function(){this.dispatchEvent(new K(Yc,this))};var Ok=function(a,b){K.call(this,a,b)};B(Ok,K);var Pk=function(a,b,c,d){d=d||pi();var f=d.dc(Kb,{style:Ff});b=d.rb(b);b.parentNode.replaceChild(f,b);f.appendChild(b);this.nb=f;this.O=null;Nk.call(this,a,b,c,void 0,d);a=this.W;this.nb.style.display=a?e:t;this.Lc(a)};B(Pk,Nk);u=Pk.prototype;u.Df=500;u.Cf=function(a){return 1-Math.pow(1-a,3)};
u.Lb=function(a){if(this.W!=a||this.O){this.nb.style.display==t&&(this.nb.style.display=e);var b=this.T.offsetHeight,c=0;this.O?(a=this.W,Ti(this.O),this.O.stop(!1),c=b-Math.abs(parseInt(this.T.style.marginTop,10))):c=a?0:b;this.Lc(a);this.O=new Gk([0,c],[0,a?b:0],this.Df,this.Cf);M(this.O,[md,ed,de],this.Mg,!1,this);M(this.O,de,A(this.Ng,this,a));this.O.play(!1)}};u.Mg=function(a){var b=this.T;b.style.marginTop=a.y-b.offsetHeight+Pf};
u.Ng=function(a){a&&(this.T.style.marginTop=ab);Ti(this.O);this.we(a);this.O=null;a||(this.nb.style.display=t);this.dispatchEvent(new Ok(xg,this,a))};var Qk=null;var U=new rk;x("BLOG_CMT_OpenIdIdentityFactory",sk,void 0);x("BLOG_CMT_LoggedInGaiaIdentity",kk,void 0);x("BLOG_CMT_NotLoggedInGaiaIdentityFactory",nk,void 0);x("BLOG_CMT_GenericOpenIdIdentityFactory",vk,void 0);x("BLOG_CMT_NameUrlIdentityFactory",qk,void 0);x("BLOG_CMT_AnonymousIdentityFactory",xj,void 0);x("BLOG_CMT_onPost",function(){yk();return U.Zg()},void 0);x("BLOG_CMT_onPreview",function(){return U.$g()},void 0);x("BLOG_CMT_onCommentBodyChange",function(){},void 0);
x("BLOG_CMT_onCancel",function(){return U.Qg()},void 0);x("BLOG_CMT_onSelectorChange",function(){return U.zc()},void 0);x("BLOG_CMT_onContinue",function(){return U.Rg()},void 0);x("BLOG_CMT_onEdit",function(){return U.Tg()},void 0);x("BLOG_CMT_addIdentity",function(a){return U.$b(a)},void 0);x("BLOG_CMT_addAndSelectIdentity",function(a){return U.ed(a)},void 0);x("BLOG_CMT_addIdentityFactory",function(a){return U.ja(a)},void 0);x("BLOG_CMT_addNameUrlIdentityFactory",function(){return U.zf()},void 0);
x("BLOG_CMT_addAnonIdentity",function(){return U.yf()},void 0);x("BLOG_CMT_addNotLoggedInGaiaIdentity",function(){return U.Af()},void 0);x("BLOG_CMT_init",function(a,b){Vj(document.location.href);U.kh();U.zc();U.$d();ik(a,b);I(gg).value==yg&&(I(gg).value=ne,Zj(I(cd),Nf));Uj();return!0},void 0);x("BLOG_CMT_addOpenIdIdentityFactories",function(){U.ja(new sk(Ub,He,Wb,Xb));U.ja(new sk(zc,Ie,Ac,Bc));U.ja(new sk(tc,Je,wc,xc));U.ja(new sk(wb,Ge,wb,xb));U.ja(new vk)},void 0);
x("BLOG_CMT_createPhotoZippy",function(a,b){I(a)&&I(b)&&(Qk=new Pk(a,b))},void 0);x("BLOG_CMT_closePhotoZippy",function(){null!=Qk&&Qk.collapse()},void 0);x("BLOG_CMT_finalizeBG",function(){window.kd&&window.kd.invoke(function(a){document.getElementById(od).value=a})},void 0);
x("BLOG_CMT_getBG",function(){var a=new yj(Za),b=document.getElementById(od).value;b&&a.Mb(od,b);b=null;window.navigator.appName==ac&&(document.documentMode?b=document.documentMode:(b=5,document.compatMode&&document.compatMode==Fb&&(b=7)));b&&a.Mb(Qe,b);document.getElementById(Hf)&&a.Mb(Gf,bb);Ij&&a.Mb(nd,Ij);pj(a,function(){if(this.Sa()){var a=eval(this.dg());a instanceof Object&&a.length&&(1<a.length&&(eval(a[1]),Ij=a[2]),window.kd=new botguard.bg(a[0]))}})},void 0);
x("BLOG_CMT_setBG",function(a){Ij=a},void 0);x("BLOG_CMT_subscription.toggle",function(){if(!fk){fk=!0;var a=I(Id);pj(a.action,function(){fk=!1;if(this.Sa()){var a=this.Hd();null!=a.errorMessage?T(3,a.errorMessage,!0):Wj(a.statusMessage);ik(a.can_subscribe,a.is_subscribed)}else T(3,Ab,!0)},lc,ek(a))}},void 0);x("BLOG_CMT_showStatusMessage",Wj,void 0);x("BLOG_CMT_showPostErrorMessage",function(a){T(4,a,!0)},void 0);x("BLOG_CMT_hidePreview",function(){yk();U.Xa();Tj()},void 0);x("BLOG_xhr",O,void 0);
O.send=pj;O.prototype.isSuccess=O.prototype.Sa;O.prototype.getResponseJson=O.prototype.Hd;x("$",I,void 0);function Rk(a){return function(b){var c=-1;try{c=b.status}catch(d){}return 500<=c?(b.responseText.length?document.body.innerHTML=b.responseText:window.alert(LayoutsMessages.SERVER_ERROR),!1):a?a(b):!0}};var Tk=function(a,b,c){var d=a.ownerDocument;a=Sk(d,a,Xd,Ig);a=Sk(d,a,Xd,Jg);a=Sk(d,a,Xd,Kg);a=Sk(d,a,Xd,Hg);var f=Sk(d,a,Xd,$e);b=b._GetHelper();var g=b._GetData();f.appendChild(d.createTextNode(g[$e]));a=Sk(d,a,Uc,ae);var k=b._GenerateWidgetMetadata();a.setAttribute(De,k.quickEditUrl);a.target=Bd;a.onclick=function(){return c._PopupConfig(d.getElementById(k.instanceId))};a.appendChild(d.createTextNode(g[Zd]))},Sk=function(a,b,c,d){a=a.createElement(c);a.className=d;b.appendChild(a);return a};var Uk=function(){this.gh={};this.be={};this.Cc={};this.Mc=null;this.ke=[]};Wg(Uk);Uk.prototype.Cd=function(a,b){return a+Hc+b+Ra};var Vk=function(a){eval(a)};Uk.prototype.Nd=function(a,b){x(Jc,Vk,void 0);this.Mc=a.replace(/\.js$/,e);b&&(this.Cd=b);Bh(this.ke,function(a){this.Eg(a)},this);Fh(this.ke)};Uk.prototype.ih=function(a,b,c){var d=this.be,f=this.gh;d[a]||(d[a]={});if(c)d[a][b]=c;else if(f[a]){for(b=0;b<f[a].length;++b)(0,f[a][b][1])(d[a][f[a][b][0]]);delete f[a];delete this.Cc[a]}};
Uk.prototype.Eg=function(a){gj(function(){if(!this.be[a]){yh(this.Mc);var b=this.Cd(this.Mc,a),c=Ph(this.Cc,b);this.Cc[a]=b;c||(b=ti(oc,{type:ug,src:b}),document.body.appendChild(b))}},0,this)};var Wk=function(){this.J=[];this.P=[]};u=Wk.prototype;u.Fg=function(){0==this.J.length&&(this.J=this.P,this.J.reverse(),this.P=[])};u.enqueue=function(a){this.P.push(a)};u.dequeue=function(){this.Fg();return this.J.pop()};u.s=function(){return this.J.length+this.P.length};u.isEmpty=function(){return 0==this.J.length&&0==this.P.length};u.clear=function(){this.J=[];this.P=[]};u.contains=function(a){return E(this.J,a)||E(this.P,a)};
u.remove=function(a){var b;b=this.J;var c=Ah(b,a);0<=c?(Gh(b,c),b=!0):b=!1;return b||Hh(this.P,a)};u.u=function(){for(var a=[],b=this.J.length-1;0<=b;--b)a.push(this.J[b]);for(var c=this.P.length,b=0;b<c;++b)a.push(this.P[b]);return a};var Xk=function(a,b){J.call(this);this.ae=a||0;this.Gb=b||10;if(this.ae>this.Gb)throw Error("[goog.structs.Pool] Min can not be greater than max");this.Y=new Wk;this.ea=new ej;this.delay=0;this.rc=null;this.fb()};B(Xk,J);u=Xk.prototype;u.sb=function(){var a=fh();if(!(null!=this.rc&&a-this.rc<this.delay)){var b=this.jh();b&&(this.rc=a,this.ea.add(b));return b}};u.Gc=function(a){return this.ea.remove(a)?(this.Zb(a),!0):!1};
u.jh=function(){for(var a;0<this.Bd()&&(a=this.Y.dequeue(),!this.yc(a));)this.fb();!a&&this.s()<this.Gb&&(a=this.ec());return a};u.Zb=function(a){this.ea.remove(a);this.yc(a)&&this.s()<this.Gb?this.Y.enqueue(a):this.gc(a)};u.fb=function(){for(var a=this.Y;this.s()<this.ae;)a.enqueue(this.ec());for(;this.s()>this.Gb&&0<this.Bd();)this.gc(a.dequeue())};u.ec=function(){return{}};u.gc=function(a){if(typeof a.la==q)a.la();else for(var b in a)a[b]=null};u.yc=function(a){return typeof a.Gf==q?a.Gf():!0};
u.contains=function(a){return this.Y.contains(a)||this.ea.contains(a)};u.s=function(){return this.Y.s()+this.ea.s()};u.Yf=function(){return this.ea.s()};u.Bd=function(){return this.Y.s()};u.isEmpty=function(){return this.Y.isEmpty()&&this.ea.isEmpty()};u.l=function(){Xk.h.l.call(this);if(0<this.Yf())throw Error("[goog.structs.Pool] Objects not released");delete this.ea;for(var a=this.Y;!a.isEmpty();)this.gc(a.dequeue());delete this.Y};var Yk=function(a,b){this.Xd=a;this.Qc=b};Yk.prototype.getKey=function(){return this.Xd};Yk.prototype.clone=function(){return new Yk(this.Xd,this.Qc)};var Zk=function(a){this.M=[];a&&this.ug(a)};u=Zk.prototype;u.Od=function(a,b){var c=this.M;c.push(new Yk(a,b));this.Kg(c.length-1)};u.ug=function(a){var b;if(a instanceof Zk){if(b=a.K(),a=a.u(),0>=this.s()){for(var c=this.M,d=0;d<b.length;d++)c.push(new Yk(b[d],a[d]));return}}else b=Nh(a),a=Mh(a);for(d=0;d<b.length;d++)this.Od(b[d],a[d])};u.remove=function(){var a=this.M,b=a.length,c=a[0];if(!(0>=b))return 1==b?Fh(a):(a[0]=a.pop(),this.Hg(0)),c.Qc};
u.Hg=function(a){for(var b=this.M,c=b.length,d=b[a];a<c>>1;){var f=this.ag(a),g=this.fg(a),f=g<c&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>d.getKey())break;b[a]=b[f];a=f}b[a]=d};u.Kg=function(a){for(var b=this.M,c=b[a];0<a;){var d=this.cg(a);if(b[d].getKey()>c.getKey())b[a]=b[d],a=d;else break}b[a]=c};u.ag=function(a){return 2*a+1};u.fg=function(a){return 2*a+2};u.cg=function(a){return a-1>>1};u.u=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].Qc);return b};
u.K=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};u.ka=function(a){return Dh(this.M,function(b){return b.getKey()==a})};u.clone=function(){return new Zk(this)};u.s=function(){return this.M.length};u.isEmpty=function(){return 0==this.M.length};u.clear=function(){Fh(this.M)};var $k=function(){Zk.call(this)};B($k,Zk);$k.prototype.enqueue=function(a,b){this.Od(a,b)};$k.prototype.dequeue=function(){return this.remove()};var V=function(a,b){this.td=void 0;this.Kb=new $k;Xk.call(this,a,b)};B(V,Xk);u=V.prototype;u.sb=function(a,b){if(!a){var c=V.h.sb.call(this);c&&this.delay&&(this.td=v.setTimeout(A(this.ub,this),this.delay));return c}this.Kb.enqueue(w(b)?b:100,a);this.ub()};u.ub=function(){for(var a=this.Kb;0<a.s();){var b=this.sb();if(b)a.dequeue().apply(this,[b]);else break}};u.Zb=function(a){V.h.Zb.call(this,a);this.ub()};u.fb=function(){V.h.fb.call(this);this.ub()};
u.l=function(){V.h.l.call(this);v.clearTimeout(this.td);this.Kb.clear();this.Kb=null};var al=function(a,b,c,d){this.mc=a;this.Fa=!!d;V.call(this,b,c)};B(al,V);al.prototype.ec=function(){var a=new O,b=this.mc;b&&b.forEach(function(b,d){a.headers.set(d,b)});this.Fa&&a.Jc(!0);return a};al.prototype.yc=function(a){return!a.sa&&!a.Ab()};var bl=function(a,b,c,d,f,g){N.call(this);this.xc=w(a)?a:1;this.qa=w(f)?Math.max(0,f):0;this.Ga=new al(b,c,d,g);this.N=new aj;this.ob=new Lk(this)};B(bl,N);var cl=[Rf,p,rg,ee,Wc,wg];u=bl.prototype;u.Ic=function(a){this.qa=Math.max(0,a)};u.send=function(a,b,c,d,f,g,k,m,r,ta){if(this.N.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new dl(b,A(this.mg,this,a),c,d,f,k,w(m)?m:this.xc,r,ta);this.N.set(a,b);a=A(this.jg,this,a);this.Ga.sb(a,g);return b};
u.abort=function(a,b){var c=this.N.get(a);if(c){var d=c.Qb;c.mh(!0);b&&(d&&(this.oe(d,c.Rc),Qi(d,Rf,function(){this.Ga.Gc(d)},!1,this)),this.N.remove(a));d&&d.abort()}};u.jg=function(a,b){var c=this.N.get(a);c&&!c.Qb?(this.Bf(b,c.Rc),b.Ic(this.qa),b.ph(c.Ca),b.Jc(c.Fa),c.Qb=b,this.dispatchEvent(new el(Rf,this,a,b)),this.qe(a,b),c.cd&&b.abort()):this.Ga.Gc(b)};
u.mg=function(a,b){var c=b.target;switch(b.type){case Rf:this.qe(a,c);break;case p:return this.kg(a,c,b);case rg:this.ng(a,c);break;case wg:case ee:this.lg(a,c);break;case Wc:this.ig(a,c)}return null};u.qe=function(a,b){var c=this.N.get(a);!c||c.pd||c.lc()?(c&&(this.oe(b,c.Rc),this.N.remove(a)),this.Ga.Gc(b)):(c.sg(),b.send(c.getUrl(),c.Gg,c.getContent(),c.mc))};
u.kg=function(a,b,c){var d=this.N.get(a);if(7==b.za||b.Sa()||d.lc())if(this.dispatchEvent(new el(p,this,a,b)),d&&(d.nh(!0),d.od))return d.od.call(b,c);return null};u.ig=function(a,b){this.dispatchEvent(new el(Wc,this,a,b))};u.ng=function(a,b){this.dispatchEvent(new el(rg,this,a,b))};u.lg=function(a,b){this.N.get(a).lc()&&this.dispatchEvent(new el(ee,this,a,b))};u.oe=function(a,b,c){this.ob.Ob(a,c||cl,b)};u.Bf=function(a,b,c){this.ob.Aa(a,c||cl,b)};
u.l=function(){bl.h.l.call(this);this.Ga.la();this.Ga=null;this.ob.la();this.ob=null;this.N.clear();this.N=null};var el=function(a,b,c,d){K.call(this,a,b);this.id=c;this.Qb=d};B(el,K);var dl=function(a,b,c,d,f,g,k,m,r){this.uh=a;this.Gg=c||Pb;this.Kf=d;this.mc=f||null;this.xc=w(k)?k:1;this.jd=0;this.cd=this.pd=!1;this.Rc=b;this.od=g;this.Ca=m||e;this.Fa=!!r;this.Qb=null};u=dl.prototype;u.getUrl=function(){return this.uh};u.getContent=function(){return this.Kf};u.sg=function(){this.jd++};
u.lc=function(){return this.jd>this.xc};u.nh=function(a){this.pd=a};u.mh=function(a){this.cd=a};function fl(a,b,c,d,f,g){this.Qa=a;this.te=b;this.se=d||null;this.data=f||null;if(g){if(this.fc=g,g!=Wd&&g!=Td&&g!=Ud&&g!=Vd)throw"bad display mode: "+g;}else this.fc=Vd;this.Bb=!1}fl.prototype.$f=function(){return this.Qa};function gl(a){this.Pf=!0;this.C=a;this.Pb=null}u=gl.prototype;u.sf=function(a){this.Pb=a};u.Ve=function(){return this.C.data};u.mf=function(a){return this.C.data=a};u.pf=function(a){return this.C.Bb=a};
u.Se=function(){var a={};a.type=this.Pb.Ie;a.instanceId=this.C.Qa;a.sectionId=this.C.te;a.actionUrl=W.bc;a.quickEditUrl=W.xd+Ea+this.Pb.Ie+Da+this.C.Qa+Ca+this.C.te+va+W.Uc;return a};u.Xb=function(a,b,c,d){b=b||{};window.__wavt&&(b.xssi_token=window.__wavt);W.Xb(a,b,this.C.Qa,this.Pb.Ie,c,d)};function W(){}W.Ze=function(a,b,c){W.ha={};W.xd=a;W.bc=b;W.qj=c;W.kc={};W.Rb=new bl;W.de=0;W.Dc=0;M(W.Rb,Rf,function(){W.Dc++});M(W.Rb,p,function(){W.Dc--})};W.uf=function(a){a=W.Pe(a.document);document.body.appendChild(a)};
W.tf=function(a){W.uf(window);if(window.parent==window){var b=nc;a&&(b=a);a=W.Oe(window.document,b);document.body.appendChild(a[0]);document.body.appendChild(a[1])}};W.af=Bd;W.Ne=Bd;W.Uc="editWidget";W.Ue=function(){return W.bc};W.qf=function(a,b){W.Ac=a;W.fh=b};W.Xe=function(){return W.Ac};W.rf=function(a){W.xh=a};W.Vc=function(){return W.xh};W.nf=function(a){W.kc=a};W.Te=function(){var a={},b;for(b in W.kc){var c=W.kc[b];a[c.name]=c.data}c={};for(b in W.ha)c[b]=W.ha[b].B.C.data;a.widgets=c;return a};
W.Xc=function(a,b){var c=new gl(b),d=new window[a](c);c.sf(d);W.ha[b.Qa]=d;W.Tc(d);return d};W.gf=function(a,b){var c=W.Xc(a,b);c.B.pf(!0);return c};W.Tc=function(a){a.B.C.fc!=Vd&&(a.B.Pf=!1)};W.ra=function(a){return W.ha?W.ha[a]:null};W.Wb=function(a,b,c,d,f){var g=e;d&&(g=Da+d);a=W.xd+va+a+Ca+b+Ea+c+g;if(window.name==f)return window.location.replace(a),window.focus(),window;f=window.open(a,f,Og);f.focus();return f};
W.ef=function(a){var b=a.getAttribute(Ke),c=W.ra(b);if(c){var d=c.B.Ja;if(null!=d&&!d.closed)return d.focus(),!1}d=Kd+b;a=W.Wb(W.Uc,a.parentNode.getAttribute(Ke),a.getAttribute(Mg),b,d);c&&(c.B.Ja=a);return!1};W.ff=function(a){W.Wb(W.Ne,a.parentNode.getAttribute(Ke),a.getAttribute(Mg),a.getAttribute(Ke),W.af);return!1};W.Qe=function(a,b,c){W.ia(c,c.LayoutsMessages.DELETING);W.Zc(Pd,{},a,b)};gl.prototype.jf=function(a,b){W.ia(b,b.LayoutsMessages.SAVING);this.Xb(Ld,a)};
W.kf=function(a,b,c){a.sectionid=document.getElementById(Zf).value;W.ia(c,c.LayoutsMessages.SAVING);W.Zc(ad,a,e,b)};W.$i=function(a,b,c){C(null!=c,mf);var d=W.ra(b);C(null!=d,nf+b);d.B.C.Bb?W.kf(a,c,window):d.B.jf(a,window)};W.Xb=function(a,b,c,d,f,g){W.Yc(W.bc,a,b,c,d,f,g)};W.Zc=function(a,b,c,d,f){W.Ac&&(b.security_token=W.fh,W.Yc(W.Ac,a,b,c,d,f))};
W.Yc=function(a,b,c,d,f,g,k){b=[Zc+encodeURIComponent(b),Lg+encodeURIComponent(d),Ng+encodeURIComponent(f),Vf];for(var m in c)if(typeof c[m]==rf)for(d=c[m],f=0;f<d.length;++f)b.push(encodeURIComponent(m)+n+encodeURIComponent(d[f]));else b.push(encodeURIComponent(m)+n+encodeURIComponent(c[m]));var r=g||Rk();c=function(){r(this.a)&&window.eval(this.eg())};k==Pb?(a=0<=a.indexOf(tb)?a+l:a+tb,W.Rb.send(e+W.de++,a+b.join(l),Pb,void 0,null,null,c)):W.Rb.send(e+W.de++,a,lc,b.join(l),null,null,c)};
W.lf=function(a,b){if(a){var c=W.ra(a);c&&(c.B.Ja=b)}};W.cb=function(a,b){0==W.Dc?a.setTimeout(function(){a.close()},b):a.setTimeout(function(){W.cb(a,b)},200)};W.$e=function(a,b){a&&(W.cb(a,100),W.vf(a,b))};W.vf=function(a,b){if(a){var c=a.document.getElementById(lg);c&&(c=c.innerHTML);c&&a&&a.opener.parent&&a.opener.parent.editor&&a.opener.parent.editor.SetSaveMessage(c,b)}};
W.Wc=function(a,b,c){var d=W.ha[a];null!=c.errors?((a=d?d.B.Ja:null)||(a=window),W.ia(a,c.errors),d&&d.eb?d.eb(b,c,a):W.eb(c,a)):(C(null!=d,nf+a),d.Wc(b,c))};W.eb=function(a,b){var c=a[fe],d;for(d in c)hl(d,c[d],b.document)};W.bf=function(a,b){window.parent&&window.parent.editor&&b?W.cf(a,b):window.location.replace(window.location.href)};W.cf=function(a,b){var c=W.ra(a);c.B.mf(b.data);var d=document.getElementById(a);wi(d);Tk(d,c,W);c.B.Ja=null};
W.Ye=function(a,b,c){var d=c[kg];if(null!=c.errors)W.ia(window,c.errors),W.eb(c,window);else if(b==ad){var f;W.Ub(window)&&(window.opener&&window.opener.parent&&(f=window.opener.parent),f&&f.editor&&f.editor.HandleAddNewWidget(c));W.ia(window,d);null==window.opener?window.location=$a+c.blogID:f&&f._WidgetManager?f._WidgetManager._KillPopupDelay(window):W.cb(window,100)}else c=W.ha[a],C(null!=c),b==Pd&&(W.ia(c.B.Ja,d),W.Re(a,Ic))};
W.df=function(a){var b=W.ra(a);b&&(b.B.C.fc==Ud?top.editor.HandleDeleteWidget(b.B.C.se):(b=b.B.C.se,b.parentNode.removeChild(b)),delete W.ha[a])};W.Re=function(a,b,c){if(W.Ub(window)){var d=window.opener;c||(c=d._WidgetManager[b]);c(a);d._WidgetManager?d._WidgetManager._KillPopupDelay(window,a):W.cb(window,100)}else a=W.Vc()+ub+a,a+=xa+encodeURIComponent(b),window.location.replace(a)};W.Ub=function(a){var b=!1;try{if(a.opener){var c=Cc+a.opener.document.domain;c&&c!=Cc&&(b=!0)}}catch(d){}return b};
W.$c="status-msg-yellow-on-white";W.ia=function(a,b){a||(a=self);var c=a.document.getElementById(lg);c&&(c.innerHTML=b);(c=a.document.getElementById(kg))&&Zj(c,W.$c)};W.Nh=function(a){a||(a=self);(a=a.document.getElementById(kg))&&bk(a,W.$c)};W.yi=function(a){a&&0<a.length&&a.substring(0,4)!=Ee&&(a=Fe+a);return a};W.We=function(a,b){if(E(Yj(a),b))return a;if(a)for(var c=a.childNodes.length,d=0;d<c;d++){var f=W.We(a.childNodes.item(d),b);if(f)return f}return null};
W.Pe=function(a){a=a.createElement(Xd);a.className=rd;a.style.position=Xc;a.style.top=ab;a.style.left=ab;a.style.width=cb;a.style.height=cb;G&&!H(7)&&(a.style.height=me);a.style.zIndex=db;a.style.cursor=Od;a.onclick=W.Vb;a.onmousedown=W.Vb;a.onmouseup=W.Vb;a.style.background=Gg;a.style.filter=dd;a.style.opacity=Pa;a.innerHTML=Aa;return a};
W.Oe=function(a,b){var c=W.Sc(a,b),d=W.Sc(a,b);c.style.backgroundColor=ma;c.style.border=fb;G&&(c.style.filter=ga);c.style.opacity=Qa;d.style.border=gb;c.style.zIndex=1200;d.style.zIndex=1200;return[c,d]};
W.Sc=function(a,b){var c=a.createElement(Xd);c.style.position=Xc;c.style.top=mb;c.style.left=Na;c.style.width=lb;c.style.height=jb;c.style.margin=ab;c.style.padding=eb;c.style.fontSize=ib;c.style.textAlign=xd;c.style.color=na;c.style.fontFamily=ka;G&&(c.style.top=Ma,c.style.left=Ma,c.style.filter=ea);c.style.MozTransform=Yf;c.style.MozTransformOrigin=kb;c.style.WebkitTransform=Yf;c.style.WebkitTransformOrigin=kb;c.innerHTML=b;c.className=hg;return c};
W.Vb=function(a){a||(a=window.event);a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation());return!1};var il=function(a,b){b||(b=document);return b.getElementById(ie+a)},jl=function(a){if(a=il(a))wi(a),a.className=he},hl=function(a,b,c){if(a=il(a,c))a.innerHTML=b,a.className=ge};x("_WidgetManager",W,void 0);W._Init=W.Ze;W._SetPageActionUrl=W.qf;W._GetPageActionUrl=W.Xe;W._SetWidgetRefreshUrl=W.rf;W._GetWidgetRefreshUrl=W.Vc;W._GetCallbackUrl=W.Ue;W._DeleteWidgetFromPage=W.Qe;
W._DisplayWidget=W.Tc;W._GetWidget=W.ra;W._HandleControllerResult=W.Wc;W._HandlePageActionResult=W.Ye;W._IsOpenerReachable=W.Ub;W._SetConfigWin=W.lf;W._SetDataContext=W.nf;W._SetupPreview=W.tf;W._RegisterWidget=W.Xc;W._RegisterNewWidget=W.gf;W._PopupPaneFromParams=W.Wb;W._PopupConfig=W.ef;W._PopupToolbox=W.ff;W._KillPopupDelay=W.$e;W._OnWidgetConfigured=W.bf;W._OnWidgetDeleted=W.df;x("_WidgetInfo",fl,void 0);fl.prototype._getInstanceId=fl.prototype.$f;gl.prototype._GetData=gl.prototype.Ve;
gl.prototype._GenerateWidgetMetadata=gl.prototype.Se;W._GetAllData=W.Te;x("widget_module_provide",function(a,b,c){Uk.Zf().ih(a,b,c)},void 0);function Y(a,b,c,d,f,g,k,m){this.F=a;this.ld=b!=of?b:null;this.Vd=c;this.Td=d;this.Ud=f;this.ue=g;this.Wd=k;this.lh=m;this.xb=this.xa=-1;this.oc=null;this.Wa=300;this.wc=hb;this.I=document.getElementById(this.F+Tc);this.jb=document.getElementById(this.F+Lc);this.wb=document.getElementById(this.F+Mc);this.pc=document.getElementById(this.F+Pc);this.Md=document.getElementById(this.F+Qc);this.f=document.getElementById(this.F+Oc);this.Oa=document.getElementById(this.F+Sc);this.hd=window.frames[this.F+
Kc];this.nc=0;this.v=new Image;this.v.onload=A(this.eh,this);this.v.onerror=A(this.Ug,this);this.zd=!1;this.ua=this.w=this.Db=null;this.Fc=!1}u=Y.prototype;
u.eh=function(){this.nc=0;jl(this.F+Rc);jl(this.F+Nc);this.pc.checked&&0!=this.xa||(this.xa=this.v.width,this.xb=this.v.height,this.oc=this.v.src);var a=1,b=1;this.v.width>this.Wa&&(a=this.Wa/this.v.width);this.v.height>this.Wa&&(b=this.Wa/this.v.height);a=Math.min(a,b);this.I.style.width=Math.round(this.v.width*a)+Pf;this.I.style.height=Math.round(this.v.height*a)+Pf;this.I.src=this.v.src;this.I.style.display=e;this.wb.style.display=t;this.jb.style.display=e;this.f.disabled=!0;this.Vd&&this.Vd.call({},
this.I.src,this.oc,this.xa,this.xb)};u.Za=function(a,b,c,d){a?(hl(this.F+Nc,b),jl(this.F+Rc)):(hl(this.F+Rc,b),jl(this.F+Nc));this.I.style.display=t;this.wb.style.display=e;this.jb.style.display=t;this.f.disabled=!1;this.Td&&this.Td.call({},c,d)};u.Ug=function(){if(2>this.nc){this.nc++;var a=this.v.src;this.v.src=e;this.Ta(a)}else this.Za(this.pc.checked,WidgetMessages.SIV_INVALID_URL,this.I.src,[])};u.Ta=function(a){this.Ge();this.v.src=a};
u.Hf=function(a){a=a||window.event;window.event?(a.returnValue=!1,a.cancelBubble=!0):(a.preventDefault(),a.stopPropagation());this.I.style.display=t;this.jb.style.display=t;this.wb.style.display=e;this.f.disabled=!1;this.Oa.value=e;this.pe();this.Fc=!0;this.Ud&&this.Ud.call({})};u.qg=function(){this.pc.checked=yg;this.Oa.value=e;this.Ge();this.Jg();this.zd=!0;try{this.w.submit()}catch(a){this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.w.value,[])}this.Ig()};
u.cc=function(){var a=this.hd.document.result;if(a)if(a.hasErrors)0<a.errors.length?this.Za(!0,a.errors[0].message,this.f.value,a.errors):this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,a.errors);else{var b=Math.max(a.origWidth,a.origHeight),c=this.Kd();0!=this.xa&&-1!=c&&b>c?(b=c/b,this.xa=Math.round(a.origWidth*b),this.xb=Math.round(a.origHeight*b)):(this.xa=a.origWidth,this.xb=a.origHeight);this.oc=a.mainSrc;this.Ta(a.thumbSrc)}else this.Za(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,
[])};u.rg=function(a){9!=(a||window.event).keyCode&&(this.Md.checked=yg,null!=this.Db&&(window.clearTimeout(this.Db),this.Db=null),a=A(this.Bg,this),this.Db=window.setTimeout(a,1E3))};u.Bg=function(){if(this.Fc||this.v.src!=this.Oa.value)this.pe(),this.Ta(this.Oa.value);this.Fc=!1};u.Dg=function(a){this.Md.checked=!0;this.Oa.value=a;this.Ta(a)};
u.Ge=function(){this.I.src=Ya;this.I.style.width=this.wc;this.I.style.height=this.wc;this.I.style.display=e;this.wb.style.display=t;this.jb.style.display=t};
u.Jg=function(){if(!this.w){this.w=document.createElement(se);this.w.action=Se;this.w.method=lc;this.w.target=this.hd.name;this.w.encoding=hf;this.w.style.display=t;if(this.ld){var a=document.createElement(We);a.type=Ce;a.name=qd;a.value=this.ld;this.w.appendChild(a)}a=document.createElement(We);a.type=Ce;a.name=$f;a.id=$f;this.w.appendChild(a);a=document.createElement(We);a.type=Ce;a.name=ag;a.value=this.lh;this.w.appendChild(a);document.body.appendChild(this.w)}a=this.Kd();-1==a&&(a=1600);document.getElementById($f).value=
a;this.ua={parent:this.f.parentNode,nextSibling:this.f.nextSibling};this.f.parentNode.removeChild(this.f);this.w.appendChild(this.f)};u.oh=function(a){this.Wa=a;this.wc=a+Pf};u.Ig=function(){this.w.removeChild(this.f);this.ua&&this.ua.nextSibling?this.ua.parent.insertBefore(this.f,this.ua.nextSibling):this.ua.parent.appendChild(this.f)};
u.pe=function(){var a=document.createElement(We);a.type=oe;a.name=this.f.name;a.id=this.f.id;a.onchange=this.f.onchange;var b=this.f.nextSibling;null==b?this.f.parentNode.appendChild(a):this.f.parentNode.insertBefore(a,b);this.f.parentNode.removeChild(this.f);this.f=a};u.Kd=function(){return-1==this.ue&&this.Wd?this.Wd():this.ue};function Z(){this.Pc={}}var kl=new Z;Z.prototype.Lf=function(a,b,c,d,f,g,k,m){this.Pc[a]=new Y(a,b,eval(c),eval(d),eval(f),g,eval(k),m);return this.Pc[a]};
Z.prototype.Jd=function(a){return this.Pc[a]};Z.prototype.cc=function(a){(a=this.Jd(a))&&a.zd&&a.cc()};x("_UploadSimpleImage",kl,void 0);Z.prototype._createUsiContainer=Z.prototype.Lf;Z.prototype._getUsiContainer=Z.prototype.Jd;Z.prototype._channelResultArrived=Z.prototype.cc;Y.prototype._changeImage=Y.prototype.Hf;Y.prototype._imgUrlFileOnChange=Y.prototype.qg;Y.prototype._imgUrlTextOnKeyUp=Y.prototype.rg;Y.prototype._loadInitialUrl=Y.prototype.Dg;Y.prototype._loadImageFromUrl=Y.prototype.Ta;
Y.prototype._setPreviewSize=Y.prototype.oh; })()
